; Catalogue data embedded in jsw.prg (generated by mkcatalogue.py).
CatalogueImage
!source "bake/catalogue_rooms.asm"
catalogue_rooms_end = *

!source "bake/catalogue_sprites.asm"
catalogue_sprites_end = *
