; room 06 — Entrance to Hades
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room06_data
; --- title ---
; "Entrance to Hades"
    !pet "Entrance to Hades", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 255, 255
; spawn px py
    !byte 36, 8
; flags: nasty
    !byte FLAG_NASTY
; border RED, background YEL; (bg<<4)|border = 114 (byte $7a includes VIC bit 3)
    !byte 122

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, PUR, PUR, RED, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 10
; wall
    !byte 6
; pickup
    !byte 0
; nasty
    !byte 3
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 149 tokens, 384 cells — each byte (N<<3)|C
    !byte (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (8<<3)|0
    !byte (2<<3)|1, (2<<3)|0, (1<<3)|1, (10<<3)|0, (1<<3)|2, (8<<3)|0, (1<<3)|1, (1<<3)|0
    !byte (1<<3)|1, (4<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|2, (8<<3)|0, (1<<3)|1, (1<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (6<<3)|0
    !byte (1<<3)|2, (8<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0
    !byte (2<<3)|1, (7<<3)|0, (1<<3)|2, (8<<3)|0, (2<<3)|1, (1<<3)|3, (1<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (2<<3)|1, (6<<3)|0, (1<<3)|2, (8<<3)|0, (1<<3)|3, (3<<3)|0, (1<<3)|3
    !byte (2<<3)|0, (1<<3)|3, (7<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (15<<3)|0, (1<<3)|1
    !byte (5<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|2, (3<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1
    !byte (3<<3)|0, (2<<3)|1, (1<<3)|0, (2<<3)|1, (1<<3)|0, (2<<3)|1, (1<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1
    !byte (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (1<<3)|1, (1<<3)|3, (2<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|3, (1<<3)|0, (1<<3)|1, (1<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1, (2<<3)|0
    !byte (2<<3)|1, (1<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (3<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (2<<3)|1, (1<<3)|3, (1<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1
    !byte (1<<3)|0, (2<<3)|1, (1<<3)|0, (1<<3)|3, (1<<3)|1, (1<<3)|2, (6<<3)|0, (1<<3)|3
    !byte (5<<3)|0, (1<<3)|3, (6<<3)|0, (1<<3)|3, (3<<3)|0

; --- pickup ---
; no pickup
    !word $ffff

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; demonc: x=12 y=64 min=64 max=70 vel=2 GRN vertical set=11
    !byte 12, 64, 64, 70, 2, GRN, 1, 11
; demona: x=8 y=56 min=56 max=56 vel=0 GRN vertical set=12
    !byte 8, 56, 56, 56, 0, GRN, 1, 12
; demonb: x=12 y=56 min=56 max=56 vel=0 GRN vertical set=13
    !byte 12, 56, 56, 56, 0, GRN, 1, 13
