; room 54 — West Wing
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room54_data
; --- title ---
; "West Wing"
    !byte 22, 28, 40, 41, 56, 22, 32, 36, 30, 0

; --- meta8 ---
; conn N E S W
    !byte 56, 31, 52, 55
; spawn px py
    !byte 64, 80
; flags: ramp
    !byte FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, BLU, GRN, WHT, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $f9, $ff, $3f, $d5, $aa, $15, $4a, $84
; wall
    !byte $ac, $ae, $01, $ad, $ad, $02, $ac, $e8
; pickup
    !byte $38, $44, $44, $44, $7c, $7c, $7c, $38
; ramp
    !byte $03, $03, $0c, $0c, $30, $30, $c0, $c0

; --- rle_tilemap ---
; 30 tokens, 384 cells — each byte (N<<3)|C
    !byte (3<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (19<<3)|0, (3<<3)|1
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (31<<3)|0, (8<<3)|0, (9<<3)|1, (4<<3)|0, (10<<3)|1, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (11<<3)|0, (12<<3)|1, (1<<3)|2, (10<<3)|0, (14<<3)|2

; --- pickup ---
; screen $10c4 x=4 y=8
    !word $10c4

; --- ramp ---
; x=9 y=15 len=15 dir=0
    !byte $ef, $09

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; scroll: x=36 y=32 min=0 max=96 vel=4 CYN vertical set=29
    !byte 36, 32, 0, 96, 4, CYN, 1, 29
; chandelier: x=12 y=48 min=40 max=56 vel=0 YEL vertical set=17
    !byte 12, 48, 40, 56, 0, YEL, 1, 17
; bird: x=24 y=80 min=0 max=23 vel=-1 RED horizontal set=3
    !byte 24, 80, 0, 23, 255, RED, 0, 3
