; room 44 — Top of the house
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room44_data
; --- title ---
; "Top of the house"
    !byte 20, 41, 42, 63, 41, 32, 63, 46, 34, 31, 63, 34, 41, 47, 45, 31, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 38, 14
; spawn px py
    !byte 0, 24
; flags: ramp
    !byte FLAG_RAMP
; border PUR, background BLU; (bg<<4)|border = 100 (byte $6c includes VIC bit 3)
    !byte 108

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, PUR, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 10
; pickup
    !byte 23
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 62 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (1<<3)|2, (1<<3)|1, (1<<3)|0, (1<<3)|2
    !byte (14<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|2, (1<<3)|1, (15<<3)|0, (1<<3)|1, (6<<3)|0
    !byte (1<<3)|2, (1<<3)|1, (14<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|2, (1<<3)|1, (1<<3)|0
    !byte (1<<3)|2, (11<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|2, (1<<3)|1, (1<<3)|0, (2<<3)|2
    !byte (9<<3)|0, (1<<3)|1, (9<<3)|0, (1<<3)|2, (1<<3)|1, (1<<3)|0, (3<<3)|2, (2<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|2, (1<<3)|0, (1<<3)|1, (10<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (1<<3)|0, (9<<3)|2, (1<<3)|1, (11<<3)|0, (1<<3)|2, (1<<3)|1, (1<<3)|0, (9<<3)|2
    !byte (13<<3)|0, (1<<3)|1, (31<<3)|0, (15<<3)|0, (12<<3)|2, (12<<3)|0

; --- pickup ---
; screen $1072 x=18 y=4
    !word $1072

; --- ramp ---
; x=12 y=10 len=6 dir=0
    !byte $5a, $0c

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; flag: x=80 y=24 min=0 max=64 vel=2 CYN vertical set=39
    !byte 80, 24, 0, 64, 2, CYN, 1, 39
