; room 59 — The Yacht
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room59_data
; --- title ---
; "The Yacht"
    !byte 20, 34, 31, 63, 25, 27, 29, 34, 46, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 58, 255, 60
; spawn px py
    !byte 91, 64
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, RED, WHT, CYN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 15
; pickup
    !byte 5
; nasty
    !byte 10
; ramp
    !byte 1
; belt
    !byte 2

; --- rle_tilemap ---
; 48 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (4<<3)|1, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|3
    !byte (3<<3)|0, (1<<3)|3, (9<<3)|0, (4<<3)|1, (12<<3)|2, (2<<3)|0, (6<<3)|1, (2<<3)|0
    !byte (1<<3)|1, (12<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|2, (2<<3)|0
    !byte (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|2, (8<<3)|0, (16<<3)|2, (8<<3)|0

; --- pickup ---
; screen $115c x=12 y=14
    !word $115c

; --- ramp ---
; x=5 y=5 len=5 dir=0
    !byte $45, $05

; --- conveyor ---
; x=16 y=15 len=8 belt=-1
    !byte $7f, $10

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; saw: x=16 y=104 min=12 max=43 vel=-1 PUR horizontal set=8
    !byte 16, 104, 12, 43, 255, PUR, 0, 8
; flag: x=64 y=72 min=64 max=104 vel=-2 RED vertical set=39
    !byte 64, 72, 64, 104, 254, RED, 1, 39
