; room 48 — Nomen Luni
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room48_data
; --- title ---
; "Nomen Luni"
    !byte 14, 37, 35, 28, 36, 56, 12, 42, 36, 32, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 18, 42, 255
; spawn px py
    !byte 84, 32
; flags: ramp
    !byte FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, PUR, YEL, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 17
; pickup
    !byte 19
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 54 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (9<<3)|0, (6<<3)|2, (15<<3)|0, (1<<3)|1
    !byte (3<<3)|0, (4<<3)|2, (3<<3)|0, (2<<3)|1, (16<<3)|0, (2<<3)|2, (14<<3)|0, (3<<3)|1
    !byte (5<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (17<<3)|0, (1<<3)|1, (1<<3)|0, (2<<3)|2
    !byte (6<<3)|0, (1<<3)|2, (15<<3)|0, (2<<3)|2, (5<<3)|0, (2<<3)|2, (11<<3)|0, (2<<3)|1
    !byte (2<<3)|0, (2<<3)|2, (3<<3)|0, (4<<3)|2, (14<<3)|0, (1<<3)|1, (2<<3)|2, (4<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (1<<3)|2, (15<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (3<<3)|0
    !byte (1<<3)|2, (9<<3)|0, (14<<3)|2, (10<<3)|0, (13<<3)|2, (2<<3)|0

; --- pickup ---
; screen $114e x=22 y=13
    !word $114e

; --- ramp ---
; x=6 y=15 len=5 dir=0
    !byte $4f, $06

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; bird: x=4 y=16 min=0 max=23 vel=-1 YEL horizontal set=3
    !byte 4, 16, 0, 23, 255, YEL, 0, 3
; hootbot: x=60 y=24 min=52 max=71 vel=1 GRN horizontal set=1
    !byte 60, 24, 52, 71, 1, GRN, 0, 1
; ewok: x=68 y=96 min=56 max=96 vel=-1 YEL vertical set=7
    !byte 68, 96, 56, 96, 255, YEL, 1, 7
; moon: x=44 y=24 min=0 max=64 vel=2 CYN vertical set=15
    !byte 44, 24, 0, 64, 2, CYN, 1, 15
