; room 51 — Tool Shed
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room51_data
; --- title ---
; "Tool Shed"
    !byte 20, 41, 41, 38, 63, 19, 34, 31, 30, 0

; --- meta8 ---
; conn N E S W
    !byte 53, 49, 255, 58
; spawn px py
    !byte 0, 48
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, PUR, YEL, WHT, GRN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 10
; pickup
    !byte 3
; nasty
    !byte 7
; ramp
    !byte 0
; belt
    !byte 7

; --- rle_tilemap ---
; 48 tokens, 384 cells — each byte (N<<3)|C
    !byte (9<<3)|0, (4<<3)|2, (19<<3)|0, (5<<3)|2, (18<<3)|0, (17<<3)|2, (13<<3)|0, (1<<3)|3
    !byte (31<<3)|0, (25<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (6<<3)|2, (4<<3)|0
    !byte (1<<3)|1, (3<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1, (3<<3)|0, (8<<3)|2, (1<<3)|1
    !byte (15<<3)|0, (8<<3)|2, (15<<3)|0, (1<<3)|1, (8<<3)|2, (2<<3)|0, (1<<3)|1, (2<<3)|0
    !byte (1<<3)|1, (3<<3)|0, (1<<3)|1, (6<<3)|0, (8<<3)|2, (12<<3)|0, (1<<3)|1, (3<<3)|0
    !byte (8<<3)|2, (15<<3)|0, (1<<3)|1, (8<<3)|2, (16<<3)|0, (8<<3)|2, (16<<3)|0, (4<<3)|2

; --- pickup ---
; screen $1154 x=4 y=14
    !word $1154

; --- ramp ---
; x=1 y=7 len=8 dir=0
    !byte $77, $01

; --- conveyor ---
; x=4 y=15 len=16 belt=1
    !byte $ff, $84

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; shears: x=60 y=48 min=20 max=59 vel=-1 GRN horizontal set=16
    !byte 60, 48, 20, 59, 255, GRN, 0, 16
; multitool: x=28 y=72 min=20 max=71 vel=1 YEL horizontal set=37
    !byte 28, 72, 20, 71, 1, YEL, 0, 37
; saw: x=56 y=104 min=20 max=71 vel=-1 PUR horizontal set=8
    !byte 56, 104, 20, 71, 255, PUR, 0, 8
