; room 15 — Looks familiar...
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room15_data
; --- title ---
; "Looks familiar..."
    !byte 12, 41, 41, 37, 45, 63, 32, 27, 39, 35, 38, 35, 27, 44, 67, 67, 67, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 14, 0, 16
; spawn px py
    !byte 1, 56
; flags: nasty|arrow
    !byte FLAG_NASTY|FLAG_ARROW
; border PUR, background BLU; (bg<<4)|border = 100 (byte $6c includes VIC bit 3)
    !byte 108

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, PUR, GRN, GRN, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 11
; wall
    !byte 6
; pickup
    !byte 19
; nasty
    !byte 11
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 80 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (30<<3)|0, (3<<3)|2
    !byte (1<<3)|1, (2<<3)|0, (2<<3)|2, (1<<3)|1, (2<<3)|0, (3<<3)|2, (1<<3)|1, (2<<3)|0
    !byte (2<<3)|2, (1<<3)|1, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3
    !byte (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2
    !byte (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3
    !byte (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2
    !byte (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3
    !byte (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (26<<3)|2

; --- pickup ---
; screen $1077 x=23 y=4
    !word $1077

; --- arrow ---
; x=40 y=50 v=-1 sound=36
    !byte $32, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; guard: x=16 y=48 min=48 max=104 vel=4 YEL vertical set=10
    !byte 16, 48, 48, 104, 4, YEL, 1, 10
; guard: x=60 y=34 min=34 max=104 vel=5 CYN vertical set=10
    !byte 60, 34, 34, 104, 5, CYN, 1, 10
; guard: x=80 y=64 min=40 max=104 vel=1 GRN vertical set=10
    !byte 80, 64, 40, 104, 1, GRN, 1, 10
; bird: x=20 y=32 min=0 max=35 vel=-1 GRN horizontal set=3
    !byte 20, 32, 0, 35, 255, GRN, 0, 3
