; room 17 — On the Battlements
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room17_data
; --- title ---
; "On the Battlements"
    !byte 15, 40, 63, 46, 34, 31, 63, 2, 27, 46, 46, 38, 31, 39, 31, 40, 46, 45, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 16, 255, 18
; spawn px py
    !byte 1, 56
; flags: nasty|conveyor|arrow
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ARROW
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, YEL, GRN, GRN, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 14
; wall
    !byte 16
; pickup
    !byte 19
; nasty
    !byte 4
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 79 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (30<<3)|0, (3<<3)|2
    !byte (1<<3)|1, (2<<3)|0, (2<<3)|2, (1<<3)|1, (5<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2
    !byte (1<<3)|1, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3
    !byte (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2
    !byte (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3
    !byte (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2
    !byte (1<<3)|3, (2<<3)|0, (5<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (3<<3)|2, (1<<3)|3, (2<<3)|0, (2<<3)|2, (1<<3)|3, (2<<3)|0, (26<<3)|2

; --- pickup ---
; screen $1077 x=23 y=4
    !word $1077

; --- conveyor ---
; x=11 y=9 len=3 belt=-1
    !byte $29, $0b

; --- arrow ---
; x=40 y=66 v=-1 sound=36
    !byte $42, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; guard: x=16 y=64 min=40 max=104 vel=1 GRN vertical set=10
    !byte 16, 64, 40, 104, 1, GRN, 1, 10
; guard: x=36 y=80 min=44 max=104 vel=2 RED vertical set=10
    !byte 36, 80, 44, 104, 2, RED, 1, 10
; guard: x=60 y=48 min=48 max=96 vel=4 YEL vertical set=10
    !byte 60, 48, 48, 96, 4, YEL, 1, 10
; guard: x=80 y=34 min=34 max=104 vel=5 CYN vertical set=10
    !byte 80, 34, 34, 104, 5, CYN, 1, 10
