; room 45 — Under the Drive
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room45_data
; --- title ---
; "Under the Drive"
    !byte 21, 36, 27, 28, 39, 56, 41, 31, 28, 56, 4, 39, 32, 43, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 4, 46, 0, 6
; spawn px py
    !byte 91, 64
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, BLU, GRN, BLU, RED

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $a5, $58, $24, $42, $20, $00
; wall
    !byte $ef, $d5, $aa, $5f, $ef, $df, $ef, $f7
; pickup
    !byte $00, $00, $02, $1c, $38, $04, $7c, $3e
; nasty
    !byte $18, $18, $14, $22, $22, $55, $11, $28
; ramp
    !byte $80, $40, $a0, $50, $a8, $54, $aa, $55
; belt
    !byte $e0, $aa, $f8, $00, $ff, $ff, $66, $66

; --- rle_tilemap ---
; 47 tokens, 384 cells — each byte (N<<3)|C
    !byte (1<<3)|2, (16<<3)|0, (8<<3)|2, (16<<3)|0, (8<<3)|2, (16<<3)|0, (1<<3)|1, (7<<3)|2
    !byte (14<<3)|0, (3<<3)|1, (7<<3)|2, (17<<3)|0, (7<<3)|2, (10<<3)|0, (1<<3)|1, (9<<3)|0
    !byte (5<<3)|2, (12<<3)|0, (2<<3)|1, (6<<3)|0, (5<<3)|2, (20<<3)|0, (5<<3)|2, (6<<3)|0
    !byte (2<<3)|1, (12<<3)|0, (5<<3)|2, (9<<3)|0, (1<<3)|3, (9<<3)|0, (6<<3)|2, (18<<3)|0
    !byte (7<<3)|2, (17<<3)|0, (8<<3)|2, (16<<3)|0, (9<<3)|2, (15<<3)|0, (10<<3)|2, (3<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (3<<3)|0, (24<<3)|2

; --- pickup ---
; screen $1089 x=17 y=5
    !word $1089

; --- ramp ---
; x=1 y=5 len=10 dir=1
    !byte $95, $81

; --- conveyor ---
; x=12 y=10 len=12 belt=-1
    !byte $ba, $0c

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; moon: x=48 y=24 min=0 max=64 vel=2 CYN vertical set=15
    !byte 48, 24, 0, 64, 2, CYN, 1, 15
; domebot: x=64 y=64 min=60 max=87 vel=-1 PUR horizontal set=40
    !byte 64, 64, 60, 87, 255, PUR, 0, 40
