; room 49 — The Wine Cellar
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room49_data
; --- title ---
; "The Wine Cellar"
    !pet "The Wine Cellar", 0

; --- meta8 ---
; conn N E S W
    !byte 52, 19, 0, 51
; spawn px py
    !byte 8, 0
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, RED, CYN, YEL, CYN, BLU

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 15
; wall
    !byte 15
; pickup
    !byte 3
; nasty
    !byte 0
; ramp
    !byte 4
; belt
    !byte 4

; --- rle_tilemap ---
; 57 tokens, 384 cells — each byte (N<<3)|C
    !byte (16<<3)|0, (1<<3)|3, (2<<3)|0, (5<<3)|2, (19<<3)|0, (5<<3)|2, (4<<3)|1, (15<<3)|0
    !byte (5<<3)|2, (21<<3)|0, (3<<3)|2, (21<<3)|0, (7<<3)|2, (1<<3)|1, (3<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (2<<3)|1, (3<<3)|0, (3<<3)|1, (8<<3)|2, (19<<3)|0, (5<<3)|2, (19<<3)|0
    !byte (6<<3)|2, (1<<3)|1, (3<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1, (3<<3)|0, (4<<3)|1
    !byte (7<<3)|2, (19<<3)|0, (5<<3)|2, (19<<3)|0, (7<<3)|2, (1<<3)|1, (3<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (1<<3)|1, (2<<3)|0, (10<<3)|1, (3<<3)|2, (5<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (1<<3)|3, (8<<3)|0, (3<<3)|2, (16<<3)|0, (11<<3)|2, (12<<3)|0
    !byte (30<<3)|2

; --- pickup ---
    !word screen_base + 242

; --- ramp ---
; x=17 y=14 len=3 dir=0
    !byte $2e, $11

; --- conveyor ---
; x=20 y=12 len=4 belt=1
    !byte $3c, $94

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; monk: x=48 y=104 min=24 max=59 vel=-1 PUR horizontal set=20
    !byte 48, 104, 24, 59, 255, PUR, 0, 20
; monk: x=68 y=24 min=0 max=75 vel=-1 PUR horizontal set=20
    !byte 68, 24, 0, 75, 255, PUR, 0, 20
; monk: x=28 y=48 min=16 max=75 vel=1 YEL horizontal set=20
    !byte 28, 48, 16, 75, 1, YEL, 0, 20
; monk: x=48 y=72 min=12 max=75 vel=-1 GRN horizontal set=20
    !byte 48, 72, 12, 75, 255, GRN, 0, 20
