; room 31 — Swimming Pool
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room31_data
; --- title ---
; "Swimming Pool"
    !byte 19, 44, 32, 35, 35, 32, 36, 30, 56, 16, 37, 37, 34, 0

; --- meta8 ---
; conn N E S W
    !byte 37, 30, 0, 54
; spawn px py
    !byte 80, 80
; flags: ramp|rope
    !byte FLAG_RAMP|FLAG_ROPE
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, RED, WHT, RED, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 1
; wall
    !byte 6
; pickup
    !byte 17
; nasty
    !byte 0
; ramp
    !byte 4
; belt
    !byte 0

; --- rle_tilemap ---
; 19 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (9<<3)|0, (4<<3)|2, (16<<3)|0, (8<<3)|2, (15<<3)|0, (9<<3)|2, (14<<3)|0
    !byte (12<<3)|2, (1<<3)|1, (17<<3)|2

; --- pickup ---
; screen $110b x=3 y=11
    !word $110b

; --- ramp ---
; x=17 y=14 len=3 dir=0
    !byte $2e, $11

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; monk: x=32 y=104 min=16 max=31 vel=-1 YEL horizontal set=20
    !byte 32, 104, 16, 31, 255, YEL, 0, 20
