; room 12 — Tree Top
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room12_data
; --- title ---
; "Tree Top"
    !byte 20, 39, 28, 28, 56, 20, 37, 38, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 0, 8, 13
; spawn px py
    !byte 52, 104
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border YEL, background BLK; (bg<<4)|border = 7 (byte $0f includes VIC bit 3)
    !byte 15

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, RED, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 9
; pickup
    !byte 18
; nasty
    !byte 8
; ramp
    !byte 3
; belt
    !byte 0

; --- rle_tilemap ---
; 57 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (1<<3)|0, (1<<3)|1, (17<<3)|0
    !byte (2<<3)|1, (26<<3)|0, (2<<3)|1, (7<<3)|0, (1<<3)|1, (6<<3)|0, (3<<3)|1, (9<<3)|0
    !byte (2<<3)|1, (31<<3)|0, (19<<3)|0, (2<<3)|1, (4<<3)|0, (8<<3)|1, (7<<3)|0, (1<<3)|2
    !byte (10<<3)|0, (1<<3)|3, (1<<3)|0, (2<<3)|3, (1<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (4<<3)|0, (1<<3)|2, (5<<3)|0, (2<<3)|1, (1<<3)|0, (1<<3)|3, (1<<3)|0, (2<<3)|3
    !byte (1<<3)|0, (2<<3)|3, (1<<3)|2, (7<<3)|0, (1<<3)|2, (1<<3)|0, (2<<3)|1, (6<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (1<<3)|3, (1<<3)|0, (1<<3)|2, (5<<3)|0, (2<<3)|1, (1<<3)|2
    !byte (8<<3)|0

; --- pickup ---
; screen $103c x=12 y=2
    !word $103c

; --- ramp ---
; x=11 y=13 len=2 dir=1
    !byte $1d, $8b

; --- arrow ---
; x=40 y=66 v=-1 sound=36
    !byte $42, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; bat: x=72 y=24 min=16 max=91 vel=-1 RED horizontal set=6
    !byte 72, 24, 16, 91, 255, RED, 0, 6
; bird: x=28 y=40 min=0 max=39 vel=-1 CYN horizontal set=3
    !byte 28, 40, 0, 39, 255, CYN, 0, 3
; flower: x=32 y=80 min=0 max=67 vel=-1 YEL horizontal set=14
    !byte 32, 80, 0, 67, 255, YEL, 0, 14
