; room 18 — On the Roof
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room18_data
; --- title ---
; "On the Roof"
    !pet "On the Roof", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 17, 0, 48
; spawn px py
    !byte 1, 56
; flags: nasty|conveyor|rope
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ROPE
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, GRN, YEL, WHT, PUR

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $80, $c0, $e0, $d0, $58, $9c, $de, $cd
; wall
    !byte $ee, $07, $f8, $f7, $0f, $f0, $2f, $c0
; pickup
    !byte $01, $02, $05, $0a, $54, $28, $30, $48
; nasty
    !byte $55, $99, $dd, $cc, $55, $99, $dd, $cc
; belt
    !byte $f0, $f0, $f0, $ff, $ff, $00, $00, $ff

; --- rle_tilemap ---
; 38 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (1<<3)|0, (2<<3)|2
    !byte (1<<3)|1, (21<<3)|0, (2<<3)|2, (1<<3)|3, (1<<3)|1, (1<<3)|0, (4<<3)|2, (1<<3)|1
    !byte (14<<3)|0, (9<<3)|2, (1<<3)|3, (14<<3)|0, (9<<3)|2, (1<<3)|3, (14<<3)|0, (10<<3)|2
    !byte (1<<3)|1, (13<<3)|0, (10<<3)|2, (1<<3)|3, (13<<3)|0, (10<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (2<<3)|2, (1<<3)|1, (8<<3)|0, (17<<3)|2, (5<<3)|0, (7<<3)|2

; --- pickup ---
    !word screen_base + 306

; --- conveyor ---
; x=12 y=15 len=5 belt=1
    !byte $ec, $8b, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; rabbit: x=72 y=104 min=44 max=71 vel=-1 CYN horizontal set=5
    !byte 72, 104, 44, 71, 255, CYN, 0, 5
