; room 02 — Under the MegaTree
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room02_data
; --- title ---
; "Under the MegaTree"
    !pet "Under the MegaTree", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 1, 0, 3
; spawn px py
    !byte 44, 104
; flags: nasty
    !byte FLAG_NASTY
; border YEL, background BLK; (bg<<4)|border = 7 (byte $0f includes VIC bit 3)
    !byte 15

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, YEL, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $d7, $b3, $75, $6d, $5c, $18, $08, $04
; wall
    !byte $bd, $aa, $5d, $a2, $f3, $0a, $06, $01
; pickup
    !byte $81, $42, $24, $18, $3c, $18, $3c, $c3
; nasty
    !byte $49, $6a, $3b, $3a, $fc, $1e, $6b, $e8

; --- rle_tilemap ---
; 43 tokens, 384 cells — each byte (N<<3)|C
    !byte (6<<3)|0, (6<<3)|3, (1<<3)|0, (5<<3)|3, (6<<3)|0, (9<<3)|2, (6<<3)|3, (1<<3)|0
    !byte (3<<3)|3, (13<<3)|0, (4<<3)|3, (1<<3)|1, (2<<3)|0, (2<<3)|1, (1<<3)|3, (30<<3)|0
    !byte (4<<3)|2, (26<<3)|0, (2<<3)|1, (5<<3)|0, (1<<3)|1, (6<<3)|0, (1<<3)|1, (13<<3)|0
    !byte (1<<3)|1, (6<<3)|0, (1<<3)|1, (6<<3)|0, (6<<3)|2, (15<<3)|0, (1<<3)|1, (10<<3)|0
    !byte (2<<3)|1, (2<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (27<<3)|0, (24<<3)|1

; --- pickup ---
    !word screen_base + 20

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; rabbit: x=64 y=104 min=0 max=87 vel=-1 CYN horizontal set=5
    !byte 64, 104, 0, 87, 255, CYN, 0, 5
; bat: x=88 y=24 min=20 max=87 vel=-1 RED horizontal set=6
    !byte 88, 24, 20, 87, 255, RED, 0, 6
; pinhead: x=56 y=72 min=48 max=87 vel=-3 PUR vertical set=2
    !byte 56, 72, 48, 87, 253, PUR, 1, 2
