; room 01 — The Bridge
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room01_data
; --- title ---
; "The Bridge"
    !pet "The Bridge", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 0, 0, 2
; spawn px py
    !byte 4, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, YEL, CYN, WHT, BLU

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 0
; wall
    !byte 16
; pickup
    !byte 13
; nasty
    !byte 4
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 27 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (17<<3)|0, (2<<3)|2, (3<<3)|0, (3<<3)|2, (15<<3)|0, (3<<3)|2, (3<<3)|0
    !byte (4<<3)|2, (13<<3)|0, (4<<3)|2, (3<<3)|3, (5<<3)|2, (6<<3)|0, (5<<3)|1, (5<<3)|2
    !byte (3<<3)|0, (5<<3)|2, (6<<3)|1

; --- pickup ---
; screen $10b6 x=14 y=7
    !word $10b6

; --- ramp ---
; x=5 y=14 len=3 dir=0
    !byte $2e, $05

; --- conveyor ---
; x=10 y=15 len=3 belt=-1
    !byte $2f, $0a

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; bird: x=16 y=80 min=0 max=31 vel=-1 RED horizontal set=3
    !byte 16, 80, 0, 31, 255, RED, 0, 3
; bird: x=64 y=80 min=48 max=91 vel=1 PUR horizontal set=3
    !byte 64, 80, 48, 91, 1, PUR, 0, 3
; ufo: x=40 y=25 min=0 max=95 vel=5 GRN vertical set=4
    !byte 40, 25, 0, 95, 5, GRN, 1, 4
