; room 05 — The Security Guard
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room05_data
; --- title ---
; "The Security Guard"
    !byte 20, 34, 31, 63, 19, 31, 29, 47, 44, 35, 46, 51, 63, 7, 47, 27, 44, 30, 0

; --- meta8 ---
; conn N E S W
    !byte 10, 4, 6, 19
; spawn px py
    !byte 1, 104
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, CYN, WHT, WHT, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 16
; wall
    !byte 7
; pickup
    !byte 10
; nasty
    !byte 0
; ramp
    !byte 1
; belt
    !byte 7

; --- rle_tilemap ---
; 73 tokens, 384 cells — each byte (N<<3)|C
    !byte (1<<3)|2, (23<<3)|0, (2<<3)|2, (22<<3)|0, (3<<3)|2, (21<<3)|0, (4<<3)|2, (20<<3)|0
    !byte (5<<3)|2, (19<<3)|0, (6<<3)|2, (18<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (3<<3)|0, (4<<3)|1, (2<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1, (2<<3)|0
    !byte (1<<3)|1, (2<<3)|0, (4<<3)|1, (2<<3)|2, (3<<3)|0, (4<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (4<<3)|2, (5<<3)|0, (4<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (4<<3)|2
    !byte (8<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (11<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (31<<3)|0, (19<<3)|0, (3<<3)|2, (2<<3)|0
    !byte (20<<3)|2

; --- pickup ---
; screen $1094 x=4 y=6
    !word $1094

; --- ramp ---
; x=1 y=0 len=8 dir=0
    !byte $70, $01

; --- conveyor ---
; x=23 y=13 len=1 belt=1
    !byte $0d, $97

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; guard: x=36 y=80 min=44 max=104 vel=2 RED vertical set=10
    !byte 36, 80, 44, 104, 2, RED, 1, 10
; guard: x=48 y=64 min=40 max=104 vel=1 GRN vertical set=10
    !byte 48, 64, 40, 104, 1, GRN, 1, 10
; guard: x=60 y=48 min=48 max=96 vel=4 YEL vertical set=10
    !byte 60, 48, 48, 96, 4, YEL, 1, 10
; guard: x=72 y=80 min=44 max=104 vel=2 RED vertical set=10
    !byte 72, 80, 44, 104, 2, RED, 1, 10
