; room 50 — Watch Tower
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room50_data
; --- title ---
; "Watch Tower"
    !byte 23, 27, 46, 29, 34, 63, 20, 41, 49, 31, 44, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 16, 255
; spawn px py
    !byte 48, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLU; (bg<<4)|border = 99 (byte $6b includes VIC bit 3)
    !byte 107

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, PUR, GRN, WHT, CYN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 0
; pickup
    !byte 22
; nasty
    !byte 7
; ramp
    !byte 0
; belt
    !byte 5

; --- rle_tilemap ---
; 46 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (1<<3)|0
    !byte (1<<3)|2, (18<<3)|0, (1<<3)|2, (4<<3)|0, (1<<3)|2, (3<<3)|0, (1<<3)|3, (9<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (1<<3)|3, (1<<3)|2, (4<<3)|0, (8<<3)|2, (3<<3)|0, (1<<3)|1
    !byte (8<<3)|2, (10<<3)|0, (2<<3)|2, (4<<3)|0, (2<<3)|2, (16<<3)|0, (2<<3)|2, (2<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (2<<3)|2, (16<<3)|0, (2<<3)|2, (4<<3)|0, (2<<3)|2, (16<<3)|0
    !byte (2<<3)|2, (1<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2, (8<<3)|0

; --- pickup ---
; screen $10ec x=20 y=9
    !word $10ec

; --- ramp ---
; x=3 y=8 len=5 dir=0
    !byte $48, $03

; --- conveyor ---
; x=8 y=4 len=8 belt=1
    !byte $74, $88

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; flower: x=52 y=72 min=28 max=59 vel=1 PUR horizontal set=14
    !byte 52, 72, 28, 59, 1, PUR, 0, 14
; bird: x=28 y=56 min=20 max=87 vel=-1 YEL horizontal set=3
    !byte 28, 56, 20, 87, 255, YEL, 0, 3
