; room 58 — The Beach
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room58_data
; --- title ---
; "The Beach"
    !pet "The Beach", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 51, 255, 59
; spawn px py
    !byte 91, 48
; flags: nasty|ramp|conveyor|rope
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR|FLAG_ROPE
; border RED, background BLU; (bg<<4)|border = 98 (byte $6a includes VIC bit 3)
    !byte 106

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, YEL, YEL, CYN

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $bf, $fb, $ff, $ef, $ff, $fe
; wall
    !byte $bb, $ff, $6d, $db, $7f, $d7, $7d, $af
; pickup
    !byte $04, $05, $0b, $0b, $17, $37, $6f, $ef
; nasty
    !byte $bd, $7e, $18, $7e, $a5, $81, $c3, $bd
; ramp
    !byte $01, $03, $07, $0f, $1e, $37, $7f, $fb
; belt
    !byte $b1, $55, $ff, $bf, $bf, $bb, $55, $00

; --- rle_tilemap ---
; 32 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (25<<3)|0, (5<<3)|2
    !byte (19<<3)|0, (10<<3)|2, (14<<3)|0, (5<<3)|2, (19<<3)|0, (5<<3)|2, (19<<3)|0, (5<<3)|2
    !byte (19<<3)|0, (5<<3)|2, (5<<3)|0, (1<<3)|1, (1<<3)|3, (3<<3)|1, (1<<3)|3, (2<<3)|1
    !byte (1<<3)|3, (2<<3)|1, (1<<3)|3, (2<<3)|1, (5<<3)|2, (4<<3)|0, (15<<3)|1, (5<<3)|2

; --- pickup ---
    !word screen_base + 329

; --- ramp ---
; x=4 y=14 len=1 dir=0
    !byte $c4, $03, $00

; --- conveyor ---
; x=0 y=15 len=4 belt=-1
    !byte $e0, $49, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 0
