; room 47 — [
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room47_data
; --- title ---
; "["
    !pet "[", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 255, 255
; spawn px py
    !byte 44, 104
; flags: none
    !byte 0
; border BLK, background BLK; (bg<<4)|border = 0 (byte $08 includes VIC bit 3)
    !byte 8

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, BLK, BLK, BLK, BLK, BLK

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $00, $00, $00, $00, $00, $00, $00, $00
; wall
    !byte $00, $00, $00, $00, $00, $00, $00, $00
; pickup
    !byte $00, $00, $00, $00, $00, $00, $00, $00

; --- rle_tilemap ---
; 13 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (12<<3)|0

; --- pickup ---
; no pickup
    !word $ffff

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 0
