; room 37 — Orangery
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room37_data
; --- title ---
; "Orangery"
    !pet "Orangery", 0

; --- meta8 ---
; conn N E S W
    !byte 43, 36, 31, 56
; spawn px py
    !byte 44, 104
; flags: ramp|conveyor|arrow
    !byte FLAG_RAMP|FLAG_CONVEYOR|FLAG_ARROW
; border YEL, background BLK; (bg<<4)|border = 7 (byte $0f includes VIC bit 3)
    !byte 15

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, YEL, CYN, YEL

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $a5, $4a, $24, $02, $04, $00, $02, $00
; wall
    !byte $15, $55, $55, $24, $25, $55, $49, $22
; pickup
    !byte $02, $14, $2e, $55, $2a, $45, $2a, $14
; ramp
    !byte $01, $02, $04, $00, $10, $20, $40, $80
; belt
    !byte $c6, $aa, $a8, $2a, $59, $24, $00, $00

; --- rle_tilemap ---
; 51 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (4<<3)|0, (1<<3)|1, (31<<3)|0, (31<<3)|0, (8<<3)|0, (1<<3)|1
    !byte (20<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|1, (27<<3)|0, (2<<3)|2, (27<<3)|0, (1<<3)|2
    !byte (20<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|1, (8<<3)|0, (2<<3)|1
    !byte (7<<3)|0, (1<<3)|2, (2<<3)|1, (6<<3)|0, (1<<3)|1, (7<<3)|0, (2<<3)|1, (4<<3)|0
    !byte (1<<3)|1, (1<<3)|2, (11<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|2
    !byte (5<<3)|0, (1<<3)|1, (17<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|1, (8<<3)|0, (8<<3)|2
    !byte (3<<3)|0, (2<<3)|1, (11<<3)|0

; --- pickup ---
    !word screen_base + 44

; --- ramp ---
; x=2 y=7 len=8 dir=0
    !byte $e2, $90, $01

; --- conveyor ---
; x=22 y=10 len=2 belt=-1
    !byte $56, $45, $00

; --- arrow ---
; x=80 y=66 v=1 sound=115
    !byte $42, $50, $03, $73, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; spiral: x=60 y=32 min=0 max=96 vel=4 CYN vertical set=32
    !byte 60, 32, 0, 96, 4, CYN, 1, 32
; moon: x=36 y=72 min=64 max=104 vel=-2 RED vertical set=15
    !byte 36, 72, 64, 104, 254, RED, 1, 15
