; room 53 — Back Door
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room53_data
; --- title ---
; "Back Door"
    !byte 2, 24, 26, 33, 56, 4, 37, 37, 39, 0

; --- meta8 ---
; conn N E S W
    !byte 55, 52, 51, 0
; spawn px py
    !byte 44, 72
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, PUR, GRN, WHT, WHT, RED

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $ff, $aa, $55, $aa, $55, $00
; wall
    !byte $69, $d2, $a5, $4b, $96, $2d, $5a, $b4
; pickup
    !byte $ee, $d1, $df, $df, $df, $df, $df, $0e
; ramp
    !byte $03, $03, $0d, $0f, $36, $3d, $da, $f4
; belt
    !byte $f0, $f0, $f0, $f0, $66, $66, $00, $00

; --- rle_tilemap ---
; 29 tokens, 384 cells — each byte (N<<3)|C
    !byte (12<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2
    !byte (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (13<<3)|1, (10<<3)|0, (2<<3)|2, (21<<3)|0, (3<<3)|2
    !byte (20<<3)|0, (4<<3)|2, (19<<3)|0, (5<<3)|2, (12<<3)|0

; --- pickup ---
; screen $1144 x=12 y=13
    !word $1144

; --- ramp ---
; x=6 y=15 len=5 dir=0
    !byte $4f, $06

; --- conveyor ---
; x=12 y=15 len=12 belt=1
    !byte $bf, $8c

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 0
