; room 07 — Cuckoo's Nest
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room07_data
; --- title ---
; "Cuckoo's Nest"
    !pet "Cuckoo's Nest", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 0, 2, 8
; spawn px py
    !byte 4, 88
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, YEL, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 14
; pickup
    !byte 13
; nasty
    !byte 7
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 21 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (5<<3)|0, (2<<3)|3, (21<<3)|0, (4<<3)|1, (19<<3)|0, (5<<3)|1, (8<<3)|0, (12<<3)|2
    !byte (4<<3)|1, (19<<3)|0, (4<<3)|1, (31<<3)|0, (2<<3)|0

; --- pickup ---
    !word screen_base + 180

; --- ramp ---
; x=10 y=12 len=2 dir=0
    !byte $1c, $0a

; --- arrow ---
; x=80 y=82 v=1 sound=115
    !byte $52, $50, $03, $73, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; egg: x=48 y=64 min=36 max=63 vel=-1 CYN horizontal set=9
    !byte 48, 64, 36, 63, 255, CYN, 0, 9
; saw: x=24 y=88 min=0 max=31 vel=-1 PUR horizontal set=8
    !byte 24, 88, 0, 31, 255, PUR, 0, 8
