; room 00 — The Off Licence
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room00_data
; --- title ---
; "The Off Licence"
    !pet "The Off Licence", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 0, 0, 1
; spawn px py
    !byte 44, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, YEL, CYN, WHT, PUR

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 16
; pickup
    !byte 19
; nasty
    !byte 9
; ramp
    !byte 0
; belt
    !byte 6

; --- rle_tilemap ---
; 45 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (16<<3)|0, (18<<3)|2, (6<<3)|0, (1<<3)|2, (16<<3)|0, (1<<3)|2
    !byte (6<<3)|0, (1<<3)|2, (16<<3)|0, (1<<3)|2, (6<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|3
    !byte (13<<3)|0, (1<<3)|2, (6<<3)|0, (1<<3)|2, (16<<3)|0, (1<<3)|2, (6<<3)|0, (1<<3)|2
    !byte (16<<3)|0, (1<<3)|2, (6<<3)|0, (1<<3)|2, (16<<3)|0, (1<<3)|2, (6<<3)|0, (1<<3)|2
    !byte (16<<3)|0, (1<<3)|2, (6<<3)|0, (4<<3)|2, (10<<3)|0, (4<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (24<<3)|1

; --- pickup ---
; screen $106c x=12 y=4
    !word $106c

; --- ramp ---
; x=16 y=14 len=4 dir=0
    !byte $3e, $10

; --- conveyor ---
; x=13 y=9 len=10 belt=-1
    !byte $99, $4d

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; bubble: x=16 y=48 min=8 max=104 vel=4 CYN vertical set=0
    !byte 16, 48, 8, 104, 4, CYN, 1, 0
; hootbot: x=84 y=56 min=52 max=83 vel=-1 GRN horizontal set=1
    !byte 84, 56, 52, 83, 255, GRN, 0, 1
; pinhead: x=8 y=32 min=0 max=104 vel=2 RED vertical set=2
    !byte 8, 32, 0, 104, 2, RED, 1, 2
