; room 09 — Over the Drive
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room09_data
; --- title ---
; "Over the Drive"
    !byte 15, 43, 28, 39, 56, 41, 31, 28, 56, 4, 39, 32, 43, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 13, 8, 4, 10
; spawn px py
    !byte 88, 40
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border CYN, background BLU; (bg<<4)|border = 99 (byte $6b includes VIC bit 3)
    !byte 107

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, RED, RED, GRN, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $1f, $f3, $e1, $60, $30, $2c, $40, $80
; wall
    !byte $09, $12, $0a, $1f, $e4, $08, $08, $08
; pickup
    !byte $30, $3c, $4f, $43, $82, $86, $e4, $fc
; nasty
    !byte $42, $29, $54, $26, $87, $23, $2a, $04
; ramp
    !byte $05, $02, $04, $08, $50, $20, $40, $80

; --- rle_tilemap ---
; 37 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (2<<3)|3, (21<<3)|0, (3<<3)|3, (3<<3)|1
    !byte (21<<3)|0, (2<<3)|3, (6<<3)|0, (10<<3)|1, (14<<3)|0, (2<<3)|3, (1<<3)|2, (2<<3)|3
    !byte (1<<3)|0, (1<<3)|3, (1<<3)|2, (2<<3)|3, (15<<3)|0, (3<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (1<<3)|2, (1<<3)|3, (22<<3)|0, (2<<3)|3, (9<<3)|0, (2<<3)|1, (15<<3)|0, (2<<3)|1
    !byte (27<<3)|0, (2<<3)|1, (31<<3)|0, (31<<3)|0, (2<<3)|0

; --- pickup ---
; screen $110a x=2 y=11
    !word $110a

; --- ramp ---
; x=10 y=10 len=4 dir=0
    !byte $3a, $0a

; --- arrow ---
; x=80 y=34 v=1 sound=115
    !byte $22, $50, $03, $73, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; moon: x=16 y=72 min=64 max=110 vel=-2 RED vertical set=15
    !byte 16, 72, 64, 110, 254, RED, 1, 15
; moon: x=36 y=48 min=0 max=56 vel=1 CYN vertical set=15
    !byte 36, 48, 0, 56, 1, CYN, 1, 15
; shears: x=56 y=40 min=48 max=91 vel=1 YEL horizontal set=16
    !byte 56, 40, 48, 91, 1, YEL, 0, 16
