; room 19 — Forgotten Abbey
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room19_data
; --- title ---
; "Forgotten Abbey"
    !pet "Forgotten Abbey", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 5, 0, 49
; spawn px py
    !byte 88, 56
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, PUR, RED, PUR, CYN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 9
; pickup
    !byte 1
; nasty
    !byte 7
; ramp
    !byte 7
; belt
    !byte 1

; --- rle_tilemap ---
; 42 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|2, (18<<3)|2, (6<<3)|0, (1<<3)|3, (4<<3)|0, (1<<3)|3, (4<<3)|0, (1<<3)|3
    !byte (5<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (3<<3)|2, (21<<3)|0, (2<<3)|2
    !byte (22<<3)|0, (2<<3)|2, (19<<3)|0, (3<<3)|1, (2<<3)|2, (11<<3)|0, (1<<3)|3, (10<<3)|0
    !byte (2<<3)|2, (21<<3)|0, (1<<3)|1, (2<<3)|2, (2<<3)|1, (20<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (4<<3)|0, (18<<3)|1, (1<<3)|2, (1<<3)|1, (22<<3)|0, (3<<3)|2, (22<<3)|0, (3<<3)|2
    !byte (21<<3)|0, (24<<3)|2

; --- pickup ---
; screen $1049 x=1 y=3
    !word $1049

; --- ramp ---
; x=2 y=13 len=2 dir=0
    !byte $1d, $02

; --- conveyor ---
; x=4 y=7 len=16 belt=-1
    !byte $f7, $04

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 6
; monk: x=16 y=40 min=16 max=63 vel=1 GRN horizontal set=20
    !byte 16, 40, 16, 63, 1, GRN, 0, 20
; monk: x=40 y=40 min=40 max=87 vel=1 YEL horizontal set=20
    !byte 40, 40, 40, 87, 1, YEL, 0, 20
; monk: x=32 y=72 min=28 max=47 vel=-1 RED horizontal set=20
    !byte 32, 72, 28, 47, 255, RED, 0, 20
; monk: x=64 y=72 min=56 max=75 vel=1 WHT horizontal set=20
    !byte 64, 72, 56, 75, 1, WHT, 0, 20
; monk: x=20 y=104 min=16 max=31 vel=-1 YEL horizontal set=20
    !byte 20, 104, 16, 31, 255, YEL, 0, 20
; monk: x=44 y=104 min=40 max=79 vel=-1 BLU horizontal set=20
    !byte 44, 104, 40, 79, 255, BLU, 0, 20
