; room 46 — Tree Root
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room46_data
; --- title ---
; "Tree Root"
    !pet "Tree Root", 0

; --- meta8 ---
; conn N E S W
    !byte 3, 255, 0, 45
; spawn px py
    !byte 4, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, PUR, RED, PUR, GRN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 9
; pickup
    !byte 12
; nasty
    !byte 9
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 67 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (2<<3)|0, (22<<3)|2, (2<<3)|0, (22<<3)|2, (2<<3)|0, (22<<3)|2, (2<<3)|0
    !byte (2<<3)|2, (2<<3)|0, (18<<3)|2, (2<<3)|0, (2<<3)|2, (2<<3)|0, (4<<3)|2, (4<<3)|0
    !byte (2<<3)|2, (5<<3)|0, (3<<3)|2, (2<<3)|0, (2<<3)|2, (2<<3)|0, (4<<3)|2, (4<<3)|0
    !byte (2<<3)|2, (5<<3)|0, (3<<3)|2, (2<<3)|0, (2<<3)|2, (10<<3)|0, (2<<3)|2, (5<<3)|0
    !byte (3<<3)|2, (2<<3)|0, (2<<3)|2, (10<<3)|0, (2<<3)|2, (5<<3)|0, (1<<3)|2, (6<<3)|0
    !byte (2<<3)|1, (8<<3)|0, (2<<3)|2, (5<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (11<<3)|0, (8<<3)|1, (3<<3)|0, (2<<3)|2, (21<<3)|0, (3<<3)|2, (20<<3)|0
    !byte (4<<3)|2, (3<<3)|0, (1<<3)|3, (3<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (3<<3)|0
    !byte (1<<3)|3, (4<<3)|0, (29<<3)|2

; --- pickup ---
; screen $104e x=6 y=3
    !word $104e

; --- ramp ---
; x=18 y=14 len=5 dir=0
    !byte $4e, $12

; --- conveyor ---
; x=0 y=10 len=9 belt=-1
    !byte $8a, $40

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; razor: x=8 y=32 min=0 max=64 vel=-2 CYN vertical set=36
    !byte 8, 32, 0, 64, 254, CYN, 1, 36
; pinhead: x=36 y=56 min=48 max=96 vel=2 CYN vertical set=2
    !byte 36, 56, 48, 96, 2, CYN, 1, 2
; rabbit: x=44 y=72 min=44 max=71 vel=1 RED horizontal set=5
    !byte 44, 72, 44, 71, 1, RED, 0, 5
; jelly: x=76 y=72 min=32 max=80 vel=2 PUR vertical set=41
    !byte 76, 72, 32, 80, 2, PUR, 1, 41
