; room 26 — East Wall Base
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room26_data
; --- title ---
; "East Wall Base"
    !byte 5, 27, 45, 46, 63, 23, 27, 38, 38, 63, 2, 27, 45, 31, 0

; --- meta8 ---
; conn N E S W
    !byte 32, 255, 20, 255
; spawn px py
    !byte 16, 104
; flags: none
    !byte 0
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, GRN, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 15
; pickup
    !byte 19
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 74 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1
    !byte (3<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (1<<3)|1, (7<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1, (17<<3)|0
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (3<<3)|0, (1<<3)|1, (4<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1, (3<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0
    !byte (2<<3)|2, (12<<3)|0

; --- pickup ---
; screen $1111 x=9 y=11
    !word $1111

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; scroll: x=12 y=72 min=0 max=96 vel=-2 RED vertical set=29
    !byte 12, 72, 0, 96, 254, RED, 1, 29
; pinhead: x=28 y=88 min=0 max=104 vel=4 CYN vertical set=2
    !byte 28, 88, 0, 104, 4, CYN, 1, 2
