; room 16 — A Quirkafleeg
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room16_data
; --- title ---
; "A Quirkafleeg"
    !byte 1, 63, 17, 47, 35, 44, 37, 27, 32, 38, 31, 31, 33, 0

; --- meta8 ---
; conn N E S W
    !byte 50, 15, 0, 17
; spawn px py
    !byte 1, 56
; flags: nasty|conveyor|rope
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ROPE
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, BLU, CYN, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 11
; wall
    !byte 12
; pickup
    !byte 19
; nasty
    !byte 5
; ramp
    !byte 0
; belt
    !byte 4

; --- rle_tilemap ---
; 28 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (30<<3)|0, (4<<3)|2
    !byte (15<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2
    !byte (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0
    !byte (9<<3)|2, (1<<3)|1, (14<<3)|3, (5<<3)|2

; --- pickup ---
; screen $1077 x=23 y=4
    !word $1077

; --- conveyor ---
; x=4 y=9 len=1 belt=0
    !byte $09, $44

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; bird: x=20 y=32 min=0 max=27 vel=-1 GRN horizontal set=3
    !byte 20, 32, 0, 27, 255, GRN, 0, 3
