; room 52 — Back Stairway
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room52_data
; --- title ---
; "Back Stairway"
    !byte 2, 24, 26, 33, 56, 19, 41, 24, 32, 39, 44, 24, 45, 0

; --- meta8 ---
; conn N E S W
    !byte 54, 25, 49, 53
; spawn px py
    !byte 44, 104
; flags: ramp
    !byte FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, PUR, YEL, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 5
; wall
    !byte 5
; pickup
    !byte 18
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 23 tokens, 384 cells — each byte (N<<3)|C
    !byte (17<<3)|0, (7<<3)|2, (16<<3)|0, (8<<3)|2, (15<<3)|0, (9<<3)|1, (31<<3)|0, (29<<3)|0
    !byte (12<<3)|1, (31<<3)|0, (26<<3)|0, (15<<3)|1, (31<<3)|0, (17<<3)|0, (5<<3)|1, (1<<3)|0
    !byte (18<<3)|1, (31<<3)|0, (31<<3)|0, (10<<3)|0, (2<<3)|1, (2<<3)|0, (20<<3)|1

; --- pickup ---
; screen $10bd x=21 y=7
    !word $10bd

; --- ramp ---
; x=2 y=14 len=15 dir=0
    !byte $ee, $02

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; egg: x=68 y=104 min=36 max=91 vel=1 CYN horizontal set=9
    !byte 68, 104, 36, 91, 1, CYN, 0, 9
; tambourine: x=60 y=48 min=44 max=67 vel=-1 WHT horizontal set=24
    !byte 60, 48, 44, 67, 255, WHT, 0, 24
; moon: x=8 y=24 min=0 max=64 vel=2 CYN vertical set=15
    !byte 8, 24, 0, 64, 2, CYN, 1, 15
