; room 24 — West of Kitchen
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room24_data
; --- title ---
; "West of Kitchen"
    !pet "West of Kitchen", 0

; --- meta8 ---
; conn N E S W
    !byte 30, 23, 0, 25
; spawn px py
    !byte 44, 104
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, GRN, WHT, WHT, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 15
; pickup
    !byte 4
; nasty
    !byte 0
; ramp
    !byte 5
; belt
    !byte 5

; --- rle_tilemap ---
; 47 tokens, 384 cells — each byte (N<<3)|C
    !byte (8<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1
    !byte (23<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1, (3<<3)|0, (4<<3)|1
    !byte (2<<3)|0, (2<<3)|1, (31<<3)|0, (17<<3)|0, (1<<3)|2, (15<<3)|0, (1<<3)|1, (5<<3)|0
    !byte (2<<3)|1, (2<<3)|2, (10<<3)|0, (2<<3)|1, (4<<3)|0, (2<<3)|1, (4<<3)|0, (3<<3)|2
    !byte (5<<3)|0, (2<<3)|1, (14<<3)|0, (4<<3)|2, (20<<3)|0, (5<<3)|2, (7<<3)|0, (2<<3)|1
    !byte (8<<3)|0, (2<<3)|1, (6<<3)|2, (18<<3)|0, (7<<3)|2, (17<<3)|0, (24<<3)|2

; --- pickup ---
; screen $10e9 x=17 y=9
    !word $10e9

; --- ramp ---
; x=1 y=8 len=7 dir=0
    !byte $68, $01

; --- conveyor ---
; x=16 y=12 len=4 belt=-1
    !byte $3c, $50

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; chef: x=24 y=48 min=0 max=88 vel=2 YEL vertical set=26
    !byte 24, 48, 0, 88, 2, YEL, 1, 26
; chef: x=40 y=64 min=0 max=104 vel=-4 GRN vertical set=26
    !byte 40, 64, 0, 104, 252, GRN, 1, 26
; chef: x=56 y=96 min=0 max=104 vel=2 YEL vertical set=26
    !byte 56, 96, 0, 104, 2, YEL, 1, 26
; chef: x=80 y=32 min=8 max=104 vel=3 PUR vertical set=26
    !byte 80, 32, 8, 104, 3, PUR, 1, 26
