; room 14 — Rescue Esmerelda
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room14_data
; --- title ---
; "Rescue Esmerelda"
    !pet "Rescue Esmerelda", 0

; --- meta8 ---
; conn N E S W
    !byte 20, 44, 39, 15
; spawn px py
    !byte 0, 56
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background RED; (bg<<4)|border = 38 (byte $2e includes VIC bit 3)
    !byte 46

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, GRN, CYN, WHT, YEL

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 15
; wall
    !byte 3
; pickup
    !byte 11
; nasty
    !byte 3
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 85 tokens, 384 cells — each byte (N<<3)|C
    !byte (18<<3)|0, (1<<3)|2, (4<<3)|0, (1<<3)|2, (18<<3)|0, (1<<3)|2, (4<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (31<<3)|0, (31<<3)|0, (4<<3)|0, (1<<3)|2, (4<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (3<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (2<<3)|2, (2<<3)|0, (1<<3)|1, (2<<3)|2, (2<<3)|0, (6<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (3<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2, (10<<3)|0
    !byte (1<<3)|1, (3<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2
    !byte (10<<3)|0, (1<<3)|1, (3<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2, (2<<3)|0, (1<<3)|3
    !byte (3<<3)|2, (8<<3)|0, (1<<3)|1, (1<<3)|0, (3<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|2
    !byte (2<<3)|0, (1<<3)|3, (4<<3)|2, (6<<3)|0, (1<<3)|1, (3<<3)|0, (2<<3)|2, (2<<3)|0
    !byte (1<<3)|3, (2<<3)|2, (2<<3)|0, (1<<3)|3, (5<<3)|2, (4<<3)|0, (1<<3)|1, (4<<3)|0
    !byte (16<<3)|2, (2<<3)|0, (1<<3)|1, (3<<3)|0, (2<<3)|2

; --- pickup ---
    !word screen_base + 66

; --- ramp ---
; x=19 y=8 len=4 dir=0
    !byte $38, $13

; --- conveyor ---
; x=16 y=4 len=4 belt=1
    !byte $34, $90

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; clive: x=8 y=48 min=48 max=96 vel=4 YEL vertical set=18
    !byte 8, 48, 48, 96, 4, YEL, 1, 18
; clive: x=28 y=64 min=40 max=104 vel=1 GRN vertical set=18
    !byte 28, 64, 40, 104, 1, GRN, 1, 18
; bird: x=20 y=32 min=0 max=35 vel=-1 GRN horizontal set=3
    !byte 20, 32, 0, 35, 255, GRN, 0, 3
; esmerelda: x=64 y=8 min=0 max=16 vel=2 WHT vertical set=19
    !byte 64, 8, 0, 16, 2, WHT, 1, 19
