; room 16 — A Quirkafleeg
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room16_data
; --- title ---
; "A Quirkafleeg"
    !pet "A Quirkafleeg", 0

; --- meta8 ---
; conn N E S W
    !byte 50, 15, 0, 17
; spawn px py
    !byte 1, 56
; flags: nasty|conveyor|rope
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ROPE
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, BLU, CYN, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $cc, $44, $22, $33, $aa, $66, $22, $11
; wall
    !byte $d8, $09, $ff, $23, $2e, $fb, $88, $7f
; pickup
    !byte $18, $24, $18, $2c, $5e, $5e, $e7, $66
; nasty
    !byte $40, $e4, $4e, $44, $44, $44, $ee, $ff
; belt
    !byte $80, $40, $20, $30, $a8, $64, $22, $11

; --- rle_tilemap ---
; 28 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (30<<3)|0, (4<<3)|2
    !byte (15<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2
    !byte (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0, (9<<3)|2, (1<<3)|1, (14<<3)|0
    !byte (9<<3)|2, (1<<3)|1, (14<<3)|3, (5<<3)|2

; --- pickup ---
    !word screen_base + 119

; --- conveyor ---
; x=4 y=9 len=1 belt=0
    !byte $24, $03, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; bird: x=20 y=32 min=0 max=27 vel=-1 GRN horizontal set=3
    !byte 20, 32, 0, 27, 255, GRN, 0, 3
