; room 27 — The Chapel
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room27_data
; --- title ---
; "The Chapel"
    !pet "The Chapel", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 21, 28
; spawn px py
    !byte 1, 96
; flags: ramp
    !byte FLAG_RAMP
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, BLU, RED, WHT, YEL, BLK

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $b6, $b6, $b6, $b6, $b6, $b6, $b6, $b6
; wall
    !byte $57, $da, $ff, $da, $57, $bf, $22, $bf
; pickup
    !byte $10, $30, $38, $6c, $c6, $c6, $6c, $10
; ramp
    !byte $03, $00, $0c, $00, $30, $00, $c0, $00

; --- rle_tilemap ---
; 49 tokens, 384 cells — each byte (N<<3)|C
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (18<<3)|0, (1<<3)|2
    !byte (3<<3)|0, (1<<3)|1, (1<<3)|2, (17<<3)|0, (2<<3)|2, (3<<3)|0, (1<<3)|1, (1<<3)|2
    !byte (16<<3)|0, (3<<3)|2, (3<<3)|0, (1<<3)|1, (1<<3)|2, (15<<3)|0, (4<<3)|2, (3<<3)|0
    !byte (1<<3)|1, (1<<3)|2, (14<<3)|0, (5<<3)|2, (3<<3)|0, (1<<3)|1, (1<<3)|2, (22<<3)|0
    !byte (1<<3)|1, (1<<3)|2, (22<<3)|0, (1<<3)|1, (21<<3)|2, (2<<3)|0, (22<<3)|2, (2<<3)|0
    !byte (2<<3)|2

; --- pickup ---
    !word screen_base + 166

; --- ramp ---
; x=11 y=13 len=7 dir=0
    !byte $ab, $8f, $01

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 5
; demonc: x=80 y=64 min=16 max=104 vel=1 GRN vertical set=11
    !byte 80, 64, 16, 104, 1, GRN, 1, 11
; demona: x=76 y=48 min=0 max=88 vel=1 GRN vertical set=12
    !byte 76, 48, 0, 88, 1, GRN, 1, 12
; demonb: x=80 y=48 min=0 max=88 vel=1 GRN vertical set=13
    !byte 80, 48, 0, 88, 1, GRN, 1, 13
; scroll: x=24 y=64 min=56 max=80 vel=-1 GRN vertical set=29
    !byte 24, 64, 56, 80, 255, GRN, 1, 29
; monk: x=32 y=96 min=0 max=35 vel=-1 PUR horizontal set=20
    !byte 32, 96, 0, 35, 255, PUR, 0, 20
