; room 30 — The Banyan Tree
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room30_data
; --- title ---
; "The Banyan Tree"
    !byte 20, 31, 28, 56, 2, 24, 36, 45, 24, 36, 56, 20, 39, 28, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 36, 29, 255, 31
; spawn px py
    !byte 8, 16
; flags: ramp
    !byte FLAG_RAMP
; border PUR, background BLK; (bg<<4)|border = 4 (byte $0c includes VIC bit 3)
    !byte 12

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, BLU, RED, BLK, YEL, BLK

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 8
; wall
    !byte 2
; pickup
    !byte 7
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 60 tokens, 384 cells — each byte (N<<3)|C
    !byte (10<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (1<<3)|2, (1<<3)|1, (22<<3)|0
    !byte (1<<3)|2, (2<<3)|1, (21<<3)|0, (6<<3)|1, (21<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1
    !byte (20<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (17<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (14<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (11<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (19<<3)|2, (2<<3)|1, (8<<3)|2, (14<<3)|0, (2<<3)|1, (8<<3)|2, (14<<3)|0
    !byte (2<<3)|1, (8<<3)|2, (16<<3)|1, (3<<3)|2

; --- pickup ---
; screen $1155 x=5 y=14
    !word $1155

; --- ramp ---
; x=2 y=11 len=8 dir=0
    !byte $7b, $02

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; spiral: x=32 y=64 min=56 max=80 vel=-1 GRN vertical set=32
    !byte 32, 64, 56, 80, 255, GRN, 1, 32
; elf: x=44 y=48 min=40 max=80 vel=2 PUR vertical set=33
    !byte 44, 48, 40, 80, 2, PUR, 1, 33
; chip: x=56 y=76 min=40 max=80 vel=1 CYN vertical set=34
    !byte 56, 76, 40, 80, 1, CYN, 1, 34
; saw: x=72 y=80 min=68 max=91 vel=-1 YEL horizontal set=8
    !byte 72, 80, 68, 91, 255, YEL, 0, 8
