; room 10 — The Front Door
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room10_data
; --- title ---
; "The Front Door"
    !pet "The Front Door", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 9, 5, 11
; spawn px py
    !byte 0, 96
; flags: ramp
    !byte FLAG_RAMP
; border RED, background CYN; (bg<<4)|border = 50 (byte $3a includes VIC bit 3)
    !byte 58

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, RED, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 10
; wall
    !byte 3
; pickup
    !byte 23
; nasty
    !byte 0
; ramp
    !byte 5
; belt
    !byte 0

; --- rle_tilemap ---
; 16 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (12<<3)|2, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (18<<3)|0, (2<<3)|1, (22<<3)|0, (3<<3)|2, (21<<3)|0

; --- pickup ---
; screen $106b x=11 y=4
    !word $106b

; --- ramp ---
; x=2 y=14 len=2 dir=0
    !byte $1e, $02

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 0
