; room 43 — Conservatory Roof
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room43_data
; --- title ---
; "Conservatory Roof"
    !byte 3, 37, 36, 40, 28, 39, 43, 24, 41, 37, 39, 45, 56, 18, 37, 37, 29, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 42, 37, 0
; spawn px py
    !byte 44, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, CYN, PUR, WHT, CYN

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ac, $53, $2a, $d0, $8a, $24, $22, $04
; wall
    !byte $f7, $ef, $00, $00, $00, $66, $66, $00
; pickup
    !byte $18, $18, $f8, $3c, $7e, $60, $60, $7e
; nasty
    !byte $da, $d5, $7f, $2e, $11, $1f, $0a, $1b
; ramp
    !byte $01, $02, $04, $10, $08, $20, $40, $80
; belt
    !byte $ac, $53, $2a, $d0, $8a, $24, $22, $04

; --- rle_tilemap ---
; 23 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (29<<3)|0, (8<<3)|2, (17<<3)|0
    !byte (1<<3)|3, (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (23<<3)|0, (1<<3)|1, (24<<3)|0, (4<<3)|1, (17<<3)|0, (1<<3)|1, (6<<3)|0

; --- pickup ---
; screen $10d4 x=20 y=8
    !word $10d4

; --- ramp ---
; x=7 y=15 len=9 dir=0
    !byte $8f, $07

; --- conveyor ---
; x=20 y=13 len=4 belt=1
    !byte $3d, $94

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; wirecutter: x=64 y=88 min=52 max=91 vel=-1 RED horizontal set=23
    !byte 64, 88, 52, 91, 255, RED, 0, 23
; shears: x=68 y=40 min=60 max=91 vel=1 YEL horizontal set=16
    !byte 68, 40, 60, 91, 1, YEL, 0, 16
