; room 40 — Dr Jones' dream
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room40_data
; --- title ---
; "Dr Jones' dream"
    !byte 4, 44, 63, 10, 41, 40, 31, 45, 65, 63, 30, 44, 31, 27, 39, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 39, 0, 41
; spawn px py
    !byte 90, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte PUR, RED, PUR, PUR, CYN, GRN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 6
; wall
    !byte 12
; pickup
    !byte 2
; nasty
    !byte 7
; ramp
    !byte 2
; belt
    !byte 7

; --- rle_tilemap ---
; 96 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (27<<3)|0, (1<<3)|3, (3<<3)|2, (20<<3)|0, (6<<3)|2, (18<<3)|0, (1<<3)|2
    !byte (6<<3)|1, (11<<3)|0, (1<<3)|3, (4<<3)|2, (1<<3)|0, (1<<3)|3, (3<<3)|1, (1<<3)|0
    !byte (3<<3)|1, (10<<3)|0, (7<<3)|2, (2<<3)|0, (1<<3)|1, (4<<3)|2, (10<<3)|0, (4<<3)|1
    !byte (2<<3)|0, (1<<3)|2, (1<<3)|1, (2<<3)|0, (3<<3)|2, (7<<3)|0, (1<<3)|1, (3<<3)|0
    !byte (4<<3)|1, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (2<<3)|1, (2<<3)|0, (1<<3)|2, (1<<3)|1, (2<<3)|0, (2<<3)|2, (9<<3)|0, (1<<3)|1
    !byte (2<<3)|0, (2<<3)|2, (2<<3)|1, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (1<<3)|2
    !byte (3<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|2, (2<<3)|1, (2<<3)|0
    !byte (1<<3)|2, (1<<3)|1, (2<<3)|0, (1<<3)|2, (11<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|1, (5<<3)|0, (1<<3)|1, (1<<3)|2, (5<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (1<<3)|1, (1<<3)|2, (3<<3)|0, (1<<3)|1, (10<<3)|0, (2<<3)|2, (2<<3)|1
    !byte (4<<3)|0, (1<<3)|1, (1<<3)|2, (1<<3)|1, (8<<3)|0, (6<<3)|2, (16<<3)|0, (2<<3)|2

; --- pickup ---
; screen $10b9 x=17 y=7
    !word $10b9

; --- ramp ---
; x=18 y=6 len=5 dir=0
    !byte $46, $12

; --- conveyor ---
; x=6 y=15 len=16 belt=-1
    !byte $ff, $06

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; moon: x=64 y=72 min=64 max=104 vel=-2 RED vertical set=15
    !byte 64, 72, 64, 104, 254, RED, 1, 15
; ewok: x=32 y=96 min=56 max=96 vel=-2 YEL vertical set=7
    !byte 32, 96, 56, 96, 254, YEL, 1, 7
