; room 10 — The Front Door
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room10_data
; --- title ---
; "The Front Door"
    !pet "The Front Door", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 9, 5, 11
; spawn px py
    !byte 0, 96
; flags: ramp
    !byte FLAG_RAMP
; border RED, background CYN; (bg<<4)|border = 50 (byte $3a includes VIC bit 3)
    !byte 58

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, RED, WHT, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $aa, $77, $aa, $77, $aa, $55, $aa
; wall
    !byte $df, $ef, $f1, $3e, $cf, $f6, $39, $df
; pickup
    !byte $0c, $1c, $1c, $1e, $1b, $3f, $78, $ff
; ramp
    !byte $c0, $40, $b0, $50, $ac, $54, $ab, $55

; --- rle_tilemap ---
; 16 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (12<<3)|2, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (18<<3)|0, (2<<3)|1, (22<<3)|0, (3<<3)|2, (21<<3)|0

; --- pickup ---
    !word screen_base + 107

; --- ramp ---
; x=2 y=14 len=2 dir=0
    !byte $c2, $85, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 0
