; room 32 — Halfway up E Wall
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room32_data
; --- title ---
; "Halfway up E Wall"
    !pet "Halfway up E Wall", 0

; --- meta8 ---
; conn N E S W
    !byte 38, 255, 26, 255
; spawn px py
    !byte 36, 104
; flags: ramp
    !byte FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, BLU, WHT, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $5a, $99, $bd, $5a, $3c, $5a
; wall
    !byte $cc, $ee, $bb, $33, $cc, $ee, $bb, $33
; pickup
    !byte $0e, $33, $6d, $5f, $ba, $be, $ec, $70
; ramp
    !byte $80, $c0, $e0, $70, $b8, $1c, $4e, $c7

; --- rle_tilemap ---
; 73 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0
    !byte (1<<3)|2, (5<<3)|0, (2<<3)|2, (16<<3)|0, (1<<3)|2, (4<<3)|0, (1<<3)|1, (3<<3)|2
    !byte (15<<3)|0, (2<<3)|2, (7<<3)|0, (1<<3)|2, (14<<3)|0, (2<<3)|2, (7<<3)|0, (2<<3)|2
    !byte (13<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (1<<3)|0, (6<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (4<<3)|0, (6<<3)|2, (12<<3)|0, (2<<3)|2, (3<<3)|0, (1<<3)|1, (4<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (2<<3)|2, (1<<3)|1, (7<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0
    !byte (2<<3)|2, (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1, (3<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (7<<3)|0, (1<<3)|1, (2<<3)|2
    !byte (12<<3)|0

; --- pickup ---
    !word screen_base + 108

; --- ramp ---
; x=6 y=2 len=6 dir=0
    !byte $46, $8c, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; wirecutter: x=12 y=48 min=8 max=31 vel=-1 YEL horizontal set=23
    !byte 12, 48, 8, 31, 255, YEL, 0, 23
