; room 11 — The Hall
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room11_data
; --- title ---
; "The Hall"
    !pet "The Hall", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 10, 0, 20
; spawn px py
    !byte 88, 96
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, CYN, GRN, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $00, $00, $00, $00, $00, $00
; wall
    !byte $df, $ef, $f1, $3e, $cf, $f6, $39, $df
; pickup
    !byte $02, $75, $71, $fa, $04, $08, $10, $20
; nasty
    !byte $88, $a9, $a9, $bb, $bf, $bf, $bf, $5e
; ramp
    !byte $c0, $c0, $30, $30, $0c, $0c, $03, $03

; --- rle_tilemap ---
; 29 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (24<<3)|2, (19<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (3<<3)|0, (1<<3)|1, (18<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (31<<3)|0, (5<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (3<<3)|0, (1<<3)|3, (7<<3)|0, (31<<3)|2, (17<<3)|2

; --- pickup ---
    !word screen_base + 226

; --- ramp ---
; x=1 y=8 len=6 dir=0
    !byte $01, $8d, $00

; --- arrow ---
; x=40 y=34 v=-1 sound=36
    !byte $22, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; chandelier: x=32 y=48 min=40 max=56 vel=0 YEL vertical set=17
    !byte 32, 48, 40, 56, 0, YEL, 1, 17
; bat: x=52 y=24 min=4 max=91 vel=-1 RED horizontal set=6
    !byte 52, 24, 4, 91, 255, RED, 0, 6
; bird: x=56 y=80 min=32 max=59 vel=-1 YEL horizontal set=3
    !byte 56, 80, 32, 59, 255, YEL, 0, 3
