; room 23 — The Kitchen
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room23_data
; --- title ---
; "The Kitchen"
    !byte 20, 34, 31, 63, 11, 35, 46, 29, 34, 31, 40, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 22, 0, 24
; spawn px py
    !byte 44, 104
; flags: ramp
    !byte FLAG_RAMP
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, CYN, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 15
; wall
    !byte 8
; pickup
    !byte 10
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 34 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (2<<3)|1, (2<<3)|0, (2<<3)|1, (2<<3)|0
    !byte (2<<3)|1, (31<<3)|0, (20<<3)|0, (1<<3)|1, (10<<3)|0, (2<<3)|1, (2<<3)|0, (2<<3)|1
    !byte (17<<3)|0, (1<<3)|2, (8<<3)|0, (2<<3)|1, (12<<3)|0, (2<<3)|2, (21<<3)|0, (3<<3)|2
    !byte (24<<3)|0, (2<<3)|1, (2<<3)|0, (2<<3)|1, (2<<3)|0, (2<<3)|1, (26<<3)|0, (3<<3)|1
    !byte (26<<3)|0, (31<<3)|2

; --- pickup ---
; screen $1021 x=9 y=1
    !word $1021

; --- ramp ---
; x=16 y=14 len=7 dir=0
    !byte $6e, $10

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; chef: x=8 y=32 min=8 max=104 vel=3 PUR vertical set=26
    !byte 8, 32, 8, 104, 3, PUR, 1, 26
; chef: x=24 y=96 min=0 max=104 vel=2 YEL vertical set=26
    !byte 24, 96, 0, 104, 2, YEL, 1, 26
; chef: x=40 y=64 min=0 max=104 vel=-4 GRN vertical set=26
    !byte 40, 64, 0, 104, 252, GRN, 1, 26
; chef: x=60 y=30 min=12 max=90 vel=3 PUR vertical set=26
    !byte 60, 30, 12, 90, 3, PUR, 1, 26
