; room 03 — Foot of Megatree
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room03_data
; --- title ---
; "Foot of Megatree"
    !byte 6, 37, 37, 41, 56, 37, 29, 56, 13, 28, 30, 24, 41, 39, 28, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 8, 2, 0, 4
; spawn px py
    !byte 4, 104
; flags: nasty|ramp
    !byte FLAG_NASTY|FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, YEL, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 0
; wall
    !byte 5
; pickup
    !byte 15
; nasty
    !byte 2
; ramp
    !byte 3
; belt
    !byte 0

; --- rle_tilemap ---
; 103 tokens, 384 cells — each byte (N<<3)|C
    !byte (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (7<<3)|0, (1<<3)|2
    !byte (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (7<<3)|0, (9<<3)|2
    !byte (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (7<<3)|0, (1<<3)|2
    !byte (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (4<<3)|0, (3<<3)|1
    !byte (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (6<<3)|0, (9<<3)|2, (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (2<<3)|1, (13<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (17<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (1<<3)|1, (5<<3)|0
    !byte (1<<3)|1, (9<<3)|2, (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (5<<3)|0, (2<<3)|1, (1<<3)|2, (9<<3)|0, (1<<3)|3, (5<<3)|0, (1<<3)|2, (2<<3)|1
    !byte (5<<3)|0, (1<<3)|2, (15<<3)|0, (1<<3)|2, (7<<3)|0, (1<<3)|2, (15<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (1<<3)|2, (21<<3)|0, (2<<3)|1, (31<<3)|0, (2<<3)|0, (24<<3)|1

; --- pickup ---
; screen $10f4 x=4 y=10
    !word $10f4

; --- ramp ---
; x=10 y=10 len=3 dir=1
    !byte $2a, $8a

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; ewok: x=8 y=30 min=30 max=85 vel=5 CYN vertical set=7
    !byte 8, 30, 30, 85, 5, CYN, 1, 7
; ewok: x=20 y=64 min=19 max=88 vel=3 RED vertical set=7
    !byte 20, 64, 19, 88, 3, RED, 1, 7
; saw: x=36 y=104 min=16 max=47 vel=-1 PUR horizontal set=8
    !byte 36, 104, 16, 47, 255, PUR, 0, 8
