; room 56 — West Wing Roof
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room56_data
; --- title ---
; "West Wing Roof"
    !pet "West Wing Roof", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 37, 54, 57
; spawn px py
    !byte 90, 104
; flags: nasty|arrow
    !byte FLAG_NASTY|FLAG_ARROW
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, PUR, GRN, RED, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $aa, $ff, $a4, $a4, $a7, $e4, $3c
; wall
    !byte $1e, $7b, $e1, $b7, $1e, $7b, $e1, $b7
; pickup
    !byte $00, $00, $00, $0a, $0d, $3c, $f2, $c0
; nasty
    !byte $18, $3c, $7e, $ff, $af, $55, $3a, $10

; --- rle_tilemap ---
; 44 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (20<<3)|0, (3<<3)|1, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (3<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (1<<3)|3, (6<<3)|0, (1<<3)|2, (20<<3)|1, (3<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (20<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (22<<3)|0, (1<<3)|1, (1<<3)|2, (23<<3)|0, (1<<3)|2, (20<<3)|0, (1<<3)|1, (2<<3)|0
    !byte (1<<3)|2, (16<<3)|1, (2<<3)|0, (2<<3)|1

; --- pickup ---
    !word screen_base + 244

; --- arrow ---
; x=80 y=42 v=1 sound=115
    !byte $2a, $50, $03, $73, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; saw: x=52 y=104 min=16 max=55 vel=1 PUR horizontal set=8
    !byte 52, 104, 16, 55, 1, PUR, 0, 8
; bird: x=52 y=88 min=32 max=83 vel=-1 YEL horizontal set=3
    !byte 52, 88, 32, 83, 255, YEL, 0, 3
