; room 29 — The Nightmare Room
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room29_data
; --- title ---
; "The Nightmare Room"
    !byte 20, 31, 28, 56, 14, 32, 30, 31, 41, 35, 24, 39, 28, 56, 18, 37, 37, 35, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 28, 255, 30
; spawn px py
    !byte 91, 104
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, YEL, BLK, YEL, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 2
; wall
    !byte 10
; pickup
    !byte 20
; nasty
    !byte 0
; ramp
    !byte 5
; belt
    !byte 0

; --- rle_tilemap ---
; 58 tokens, 384 cells — each byte (N<<3)|C
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (17<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|1
    !byte (11<<3)|0, (1<<3)|2, (8<<3)|0, (1<<3)|1, (14<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (11<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|1, (11<<3)|0, (1<<3)|1
    !byte (5<<3)|0, (1<<3)|2, (8<<3)|0, (1<<3)|1, (14<<3)|0, (1<<3)|2, (14<<3)|0, (1<<3)|1
    !byte (5<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|1, (11<<3)|0, (1<<3)|1
    !byte (5<<3)|0, (3<<3)|2, (6<<3)|0, (1<<3)|1, (14<<3)|0, (4<<3)|2, (21<<3)|0, (4<<3)|2
    !byte (20<<3)|0, (24<<3)|2

; --- pickup ---
; screen $10ec x=20 y=9
    !word $10ec

; --- ramp ---
; x=2 y=12 len=3 dir=1
    !byte $2c, $82

; --- conveyor ---
; x=21 y=8 len=1 belt=-1
    !byte $08, $15

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 6
; maria: x=12 y=32 min=0 max=80 vel=-2 CYN vertical set=30
    !byte 12, 32, 0, 80, 254, CYN, 1, 30
; maria: x=24 y=16 min=0 max=104 vel=1 PUR vertical set=30
    !byte 24, 16, 0, 104, 1, PUR, 1, 30
; foot: x=36 y=72 min=0 max=96 vel=2 YEL vertical set=31
    !byte 36, 72, 0, 96, 2, YEL, 1, 31
; maria: x=48 y=66 min=6 max=102 vel=-3 RED vertical set=30
    !byte 48, 66, 6, 102, 253, RED, 1, 30
; maria: x=60 y=32 min=0 max=80 vel=-2 CYN vertical set=30
    !byte 60, 32, 0, 80, 254, CYN, 1, 30
; maria: x=72 y=16 min=0 max=104 vel=1 PUR vertical set=30
    !byte 72, 16, 0, 104, 1, PUR, 1, 30
