; room 25 — Cold Store
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room25_data
; --- title ---
; "Cold Store"
    !pet "Cold Store", 0

; --- meta8 ---
; conn N E S W
    !byte 31, 24, 0, 52
; spawn px py
    !byte 44, 104
; flags: nasty|rope
    !byte FLAG_NASTY|FLAG_ROPE
; border CYN, background BLU; (bg<<4)|border = 99 (byte $6b includes VIC bit 3)
    !byte 107

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, GRN, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 16
; pickup
    !byte 6
; nasty
    !byte 7
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 40 tokens, 384 cells — each byte (N<<3)|C
    !byte (6<<3)|0, (1<<3)|3, (26<<3)|0, (1<<3)|3, (8<<3)|0, (1<<3)|3, (5<<3)|0, (3<<3)|1
    !byte (31<<3)|0, (5<<3)|0, (1<<3)|3, (4<<3)|0, (1<<3)|3, (27<<3)|0, (7<<3)|1, (31<<3)|0
    !byte (31<<3)|0, (3<<3)|0, (4<<3)|1, (16<<3)|0, (4<<3)|2, (20<<3)|0, (4<<3)|2, (20<<3)|0
    !byte (4<<3)|2, (4<<3)|1, (16<<3)|0, (4<<3)|2, (7<<3)|0, (1<<3)|3, (8<<3)|0, (2<<3)|1
    !byte (2<<3)|0, (4<<3)|2, (20<<3)|0, (4<<3)|2, (20<<3)|0, (4<<3)|2, (20<<3)|1, (4<<3)|2

; --- pickup ---
; screen $10c4 x=4 y=8
    !word $10c4

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; penguin: x=12 y=48 min=0 max=19 vel=1 GRN horizontal set=27
    !byte 12, 48, 0, 19, 1, GRN, 0, 27
; cone: x=24 y=24 min=0 max=31 vel=1 PUR horizontal set=28
    !byte 24, 24, 0, 31, 1, PUR, 0, 28
