; room 04 — The Drive
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room04_data
; --- title ---
; "The Drive"
    !pet "The Drive", 0

; --- meta8 ---
; conn N E S W
    !byte 6, 3, 45, 5
; spawn px py
    !byte 64, 104
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border PUR, background BLK; (bg<<4)|border = 4 (byte $0c includes VIC bit 3)
    !byte 12

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, GRN, CYN, RED

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $aa, $55, $aa, $ff, $ff, $55, $aa, $55
; wall
    !byte $70, $07, $77, $77, $00, $3b, $0b, $7d
; pickup
    !byte $00, $00, $04, $d2, $cb, $2b, $56, $7c
; ramp
    !byte $c0, $40, $70, $70, $0c, $74, $77, $05
; belt
    !byte $7b, $00, $ed, $00, $aa, $55, $aa, $55

; --- rle_tilemap ---
; 29 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (6<<3)|0, (3<<3)|1
    !byte (21<<3)|0, (4<<3)|2, (20<<3)|0, (5<<3)|2, (23<<3)|0, (2<<3)|2, (22<<3)|0, (3<<3)|2
    !byte (21<<3)|0, (4<<3)|2, (16<<3)|0, (2<<3)|2, (2<<3)|0, (5<<3)|2, (15<<3)|0, (2<<3)|2
    !byte (2<<3)|0, (6<<3)|2, (6<<3)|1, (2<<3)|2, (6<<3)|1

; --- pickup ---
    !word screen_base + 170

; --- ramp ---
; x=3 y=8 len=7 dir=0
    !byte $03, $8f, $00

; --- conveyor ---
; x=0 y=13 len=2 belt=1
    !byte $a0, $85, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; bird: x=20 y=40 min=0 max=23 vel=-1 CYN horizontal set=3
    !byte 20, 40, 0, 23, 255, CYN, 0, 3
; bird: x=24 y=64 min=20 max=83 vel=-1 YEL horizontal set=3
    !byte 24, 64, 20, 83, 255, YEL, 0, 3
; bird: x=64 y=88 min=48 max=83 vel=-1 GRN horizontal set=3
    !byte 64, 88, 48, 83, 255, GRN, 0, 3
; egg: x=44 y=104 min=40 max=91 vel=1 CYN horizontal set=9
    !byte 44, 104, 40, 91, 1, CYN, 0, 9
