; room 36 — A bit of tree
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room36_data
; --- title ---
; "A bit of tree"
    !byte 1, 56, 25, 32, 41, 56, 37, 29, 56, 41, 39, 28, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 42, 255, 30, 37
; spawn px py
    !byte 48, 104
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, RED, GRN, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ad, $52, $29, $00, $01, $02, $00, $00
; wall
    !byte $d6, $6b, $66, $db, $69, $6b, $d9, $6d
; pickup
    !byte $40, $a0, $38, $6c, $6c, $76, $3a, $1f
; nasty
    !byte $15, $00, $aa, $55, $aa, $00, $15, $0a
; ramp
    !byte $03, $08, $24, $10, $40, $20, $80, $80

; --- rle_tilemap ---
; 90 tokens, 384 cells — each byte (N<<3)|C
    !byte (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3
    !byte (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3
    !byte (7<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2, (5<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|3
    !byte (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3, (3<<3)|0, (2<<3)|1, (5<<3)|0, (2<<3)|2
    !byte (7<<3)|0, (2<<3)|1, (2<<3)|0, (1<<3)|3, (7<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2
    !byte (11<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3, (7<<3)|0, (2<<3)|1
    !byte (1<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|3
    !byte (4<<3)|1, (6<<3)|0, (2<<3)|2, (2<<3)|1, (9<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2
    !byte (9<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2, (7<<3)|0, (1<<3)|1
    !byte (3<<3)|0, (1<<3)|3, (10<<3)|0, (2<<3)|2, (2<<3)|0, (2<<3)|1, (7<<3)|0, (1<<3)|3
    !byte (10<<3)|0, (2<<3)|2, (11<<3)|0, (1<<3)|3, (9<<3)|0, (1<<3)|1, (2<<3)|2, (1<<3)|1
    !byte (10<<3)|0, (1<<3)|3

; --- pickup ---
; screen $109c x=12 y=6
    !word $109c

; --- ramp ---
; x=17 y=9 len=2 dir=0
    !byte $19, $11

; --- arrow ---
; x=40 y=73 v=-1 sound=36
    !byte $49, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; bird: x=4 y=16 min=0 max=35 vel=-1 YEL horizontal set=3
    !byte 4, 16, 0, 35, 255, YEL, 0, 3
; chip: x=20 y=48 min=40 max=80 vel=2 PUR vertical set=34
    !byte 20, 48, 40, 80, 2, PUR, 1, 34
