; room 59 — The Yacht
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room59_data
; --- title ---
; "The Yacht"
    !byte 20, 31, 28, 56, 23, 24, 26, 31, 41, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 58, 255, 60
; spawn px py
    !byte 91, 64
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, RED, WHT, CYN

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $bb, $dd, $dd, $ee, $00, $00, $00, $00
; wall
    !byte $bb, $77, $ee, $dd, $bb, $77, $ee, $dd
; pickup
    !byte $ce, $f1, $b9, $d5, $ef, $d7, $bb, $ff
; nasty
    !byte $7e, $bf, $bf, $6e, $2c, $2c, $ad, $ff
; ramp
    !byte $80, $40, $20, $10, $08, $04, $02, $01
; belt
    !byte $e0, $aa, $38, $01, $83, $c7, $7c, $10

; --- rle_tilemap ---
; 48 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (4<<3)|1, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|3
    !byte (3<<3)|0, (1<<3)|3, (9<<3)|0, (4<<3)|1, (12<<3)|2, (2<<3)|0, (6<<3)|1, (2<<3)|0
    !byte (1<<3)|1, (12<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|2, (2<<3)|0
    !byte (1<<3)|1, (7<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|2, (8<<3)|0, (16<<3)|2, (8<<3)|0

; --- pickup ---
; screen $115c x=12 y=14
    !word $115c

; --- ramp ---
; x=5 y=5 len=5 dir=1
    !byte $45, $85

; --- conveyor ---
; x=16 y=15 len=8 belt=-1
    !byte $7f, $10

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; saw: x=16 y=104 min=12 max=43 vel=-1 PUR horizontal set=8
    !byte 16, 104, 12, 43, 255, PUR, 0, 8
; flag: x=64 y=72 min=64 max=104 vel=-2 RED vertical set=39
    !byte 64, 72, 64, 104, 254, RED, 1, 39
