; room 28 — First Landing
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room28_data
; --- title ---
; "First Landing"
    !byte 6, 35, 44, 45, 46, 63, 12, 27, 40, 30, 35, 40, 33, 0

; --- meta8 ---
; conn N E S W
    !byte 34, 27, 22, 29
; spawn px py
    !byte 44, 104
; flags: nasty|ramp
    !byte FLAG_NASTY|FLAG_RAMP
; border PUR, background BLK; (bg<<4)|border = 4 (byte $0c includes VIC bit 3)
    !byte 12

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, BLU, YEL, WHT, BLK

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 0
; wall
    !byte 0
; pickup
    !byte 19
; nasty
    !byte 8
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 72 tokens, 384 cells — each byte (N<<3)|C
    !byte (1<<3)|2, (17<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (5<<3)|0
    !byte (1<<3)|2, (17<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (2<<3)|0
    !byte (1<<3)|3, (2<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (1<<3)|0, (3<<3)|3, (1<<3)|0
    !byte (1<<3)|2, (17<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (17<<3)|0
    !byte (1<<3)|2, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (2<<3)|0
    !byte (1<<3)|3, (2<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0
    !byte (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|2, (5<<3)|0, (1<<3)|2, (17<<3)|0
    !byte (1<<3)|2, (5<<3)|0, (1<<3)|2, (31<<3)|0, (31<<3)|0, (2<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (1<<3)|2, (1<<3)|1, (1<<3)|2, (1<<3)|1, (1<<3)|2, (15<<3)|1, (2<<3)|0, (7<<3)|2

; --- pickup ---
; screen $10eb x=19 y=9
    !word $10eb

; --- ramp ---
; x=4 y=14 len=14 dir=0
    !byte $de, $04

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; monk: x=76 y=96 min=68 max=91 vel=-1 YEL horizontal set=20
    !byte 76, 96, 68, 91, 255, YEL, 0, 20
