; room 39 — Emergency Dynamo
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room39_data
; --- title ---
; "Emergency Dynamo"
    !pet "Emergency Dynamo", 0

; --- meta8 ---
; conn N E S W
    !byte 14, 38, 0, 40
; spawn px py
    !byte 91, 24
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border RED, background BLU; (bg<<4)|border = 98 (byte $6a includes VIC bit 3)
    !byte 106

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, YEL, CYN, WHT, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 1
; wall
    !byte 17
; pickup
    !byte 9
; nasty
    !byte 6
; ramp
    !byte 0
; belt
    !byte 4

; --- rle_tilemap ---
; 74 tokens, 384 cells — each byte (N<<3)|C
    !byte (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (31<<3)|0, (22<<3)|0
    !byte (2<<3)|1, (10<<3)|0, (2<<3)|1, (3<<3)|0, (2<<3)|2, (5<<3)|0, (2<<3)|1, (10<<3)|0
    !byte (2<<3)|1, (4<<3)|0, (1<<3)|3, (5<<3)|0, (2<<3)|1, (10<<3)|0, (2<<3)|1, (4<<3)|0
    !byte (1<<3)|3, (5<<3)|0, (2<<3)|1, (10<<3)|0, (2<<3)|1, (4<<3)|0, (1<<3)|3, (5<<3)|0
    !byte (2<<3)|1, (10<<3)|0, (2<<3)|1, (4<<3)|0, (1<<3)|3, (4<<3)|0, (4<<3)|2, (8<<3)|0
    !byte (4<<3)|2, (3<<3)|0, (1<<3)|3, (4<<3)|0, (2<<3)|2, (1<<3)|0, (1<<3)|2, (8<<3)|0
    !byte (1<<3)|2, (1<<3)|0, (2<<3)|2, (3<<3)|0, (1<<3)|3, (3<<3)|0, (18<<3)|2, (2<<3)|0
    !byte (1<<3)|3, (3<<3)|0, (4<<3)|2, (1<<3)|0, (2<<3)|2, (1<<3)|0, (2<<3)|2, (1<<3)|0
    !byte (2<<3)|2, (1<<3)|0, (4<<3)|2, (2<<3)|0, (1<<3)|3, (3<<3)|0, (18<<3)|2, (2<<3)|0
    !byte (1<<3)|3, (24<<3)|2

; --- pickup ---
; screen $1006 x=6 y=0
    !word $1006

; --- ramp ---
; x=11 y=10 len=6 dir=0
    !byte $5a, $0b

; --- conveyor ---
; x=8 y=11 len=8 belt=-1
    !byte $7b, $48

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; bird: x=20 y=16 min=8 max=39 vel=-1 RED horizontal set=3
    !byte 20, 16, 8, 39, 255, RED, 0, 3
; bird: x=72 y=16 min=56 max=83 vel=1 PUR horizontal set=3
    !byte 72, 16, 56, 83, 1, PUR, 0, 3
