; room 11 — The Hall
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room11_data
; --- title ---
; "The Hall"
    !byte 20, 34, 31, 63, 8, 27, 38, 38, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 10, 0, 20
; spawn px py
    !byte 88, 96
; flags: nasty|ramp|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_ARROW
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, CYN, GRN, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 3
; pickup
    !byte 10
; nasty
    !byte 9
; ramp
    !byte 1
; belt
    !byte 0

; --- rle_tilemap ---
; 29 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (27<<3)|0, (24<<3)|2, (19<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (3<<3)|0, (1<<3)|1, (18<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (31<<3)|0, (5<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (3<<3)|0, (1<<3)|3, (7<<3)|0, (31<<3)|2, (17<<3)|2

; --- pickup ---
; screen $10e2 x=10 y=9
    !word $10e2

; --- ramp ---
; x=1 y=8 len=6 dir=0
    !byte $58, $01

; --- arrow ---
; x=40 y=34 v=-1 sound=36
    !byte $22, $28, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; chandelier: x=32 y=48 min=40 max=56 vel=0 YEL vertical set=17
    !byte 32, 48, 40, 56, 0, YEL, 1, 17
; bat: x=52 y=24 min=4 max=91 vel=-1 RED horizontal set=6
    !byte 52, 24, 4, 91, 255, RED, 0, 6
; bird: x=56 y=80 min=32 max=59 vel=-1 YEL horizontal set=3
    !byte 56, 80, 32, 59, 255, YEL, 0, 3
