; room 20 — Ballroom East
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room20_data
; --- title ---
; "Ballroom East"
    !byte 2, 24, 34, 34, 39, 37, 37, 35, 56, 5, 24, 40, 41, 0

; --- meta8 ---
; conn N E S W
    !byte 26, 11, 0, 21
; spawn px py
    !byte 88, 96
; flags: none
    !byte 0
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, WHT, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 13
; pickup
    !byte 10
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 45 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (2<<3)|0
    !byte (1<<3)|1, (5<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0
    !byte (2<<3)|2, (16<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (19<<3)|0, (10<<3)|1, (3<<3)|2
    !byte (2<<3)|0, (9<<3)|2, (9<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (23<<3)|0, (15<<3)|1
    !byte (9<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1
    !byte (23<<3)|0, (1<<3)|1, (14<<3)|0, (31<<3)|2, (17<<3)|2

; --- pickup ---
; screen $1103 x=19 y=10
    !word $1103

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; pachead: x=20 y=72 min=48 max=87 vel=-3 PUR vertical set=21
    !byte 20, 72, 48, 87, 253, PUR, 1, 21
; pachead: x=28 y=56 min=48 max=96 vel=2 CYN vertical set=21
    !byte 28, 56, 48, 96, 2, CYN, 1, 21
; pachead: x=44 y=75 min=72 max=96 vel=1 YEL vertical set=21
    !byte 44, 75, 72, 96, 1, YEL, 1, 21
; barrel: x=52 y=16 min=16 max=48 vel=1 RED vertical set=22
    !byte 52, 16, 16, 48, 1, RED, 1, 22
