; room 55 — West Bedroom
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room55_data
; --- title ---
; "West Bedroom"
    !pet "West Bedroom", 0

; --- meta8 ---
; conn N E S W
    !byte 57, 54, 53, 0
; spawn px py
    !byte 76, 80
; flags: conveyor
    !byte FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, WHT, WHT, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 12
; pickup
    !byte 6
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 66 tokens, 384 cells — each byte (N<<3)|C
    !byte (6<<3)|0, (1<<3)|1, (5<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (19<<3)|0, (2<<3)|2
    !byte (2<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|1, (6<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (19<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0, (2<<3)|1, (6<<3)|0, (1<<3)|1
    !byte (5<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (19<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (16<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (19<<3)|0, (2<<3)|2
    !byte (2<<3)|0, (1<<3)|1, (13<<3)|0, (1<<3)|1, (9<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1
    !byte (12<<3)|0, (1<<3)|1, (10<<3)|0, (1<<3)|1, (13<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|1
    !byte (13<<3)|0, (1<<3)|2, (17<<3)|1, (6<<3)|0, (8<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (10<<3)|0

; --- pickup ---
; screen $1056 x=14 y=3
    !word $1056

; --- conveyor ---
; x=20 y=3 len=2 belt=-1
    !byte $13, $14

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; razor: x=28 y=32 min=0 max=64 vel=-2 CYN vertical set=36
    !byte 28, 32, 0, 64, 254, CYN, 1, 36
; jelly: x=40 y=24 min=0 max=80 vel=1 RED vertical set=41
    !byte 40, 24, 0, 80, 1, RED, 1, 41
