; room 33 — The Bathroom
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room33_data
; --- title ---
; "The Bathroom"
    !pet "The Bathroom", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 255, 255, 34
; spawn px py
    !byte 64, 104
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, RED, YEL, YEL, WHT, CYN

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 0
; wall
    !byte 0
; pickup
    !byte 0
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 51 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (21<<3)|0, (3<<3)|2, (21<<3)|0, (3<<3)|2, (21<<3)|0, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (23<<3)|0, (1<<3)|2, (10<<3)|1, (3<<3)|0, (1<<3)|2, (9<<3)|1, (2<<3)|2
    !byte (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2, (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2, (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2, (12<<3)|0, (1<<3)|2, (9<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|2, (4<<3)|0, (2<<3)|1, (17<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (24<<3)|1

; --- pickup ---
    !word screen_base + 330

; --- ramp ---
; x=5 y=12 len=8 dir=0
    !byte $7c, $05

; --- conveyor ---
; x=16 y=14 len=3 belt=-1
    !byte $2e, $50

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; globes: x=48 y=24 min=0 max=83 vel=-1 GRN horizontal set=25
    !byte 48, 24, 0, 83, 255, GRN, 0, 25
; toilet: x=84 y=104 min=104 max=104 vel=0 WHT vertical set=35
    !byte 84, 104, 104, 104, 0, WHT, 1, 35
