; room 34 — Top Landing
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room34_data
; --- title ---
; "Top Landing"
    !byte 20, 37, 38, 56, 12, 24, 36, 27, 32, 36, 30, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 33, 28, 35
; spawn px py
    !byte 44, 16
; flags: ramp
    !byte FLAG_RAMP
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, PUR, BLK, WHT, BLK

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $aa, $55, $ff, $00, $00, $00, $00
; wall
    !byte $69, $90, $90, $69, $96, $69, $69, $96
; pickup
    !byte $18, $24, $a4, $ca, $95, $0a, $15, $0a
; ramp
    !byte $07, $02, $3c, $08, $70, $20, $c0, $80

; --- rle_tilemap ---
; 44 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|2, (18<<3)|2, (22<<3)|0, (2<<3)|2, (23<<3)|0, (1<<3)|2, (3<<3)|1, (2<<3)|0
    !byte (3<<3)|1, (2<<3)|0, (9<<3)|1, (4<<3)|0, (1<<3)|2, (19<<3)|0, (5<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (3<<3)|1, (2<<3)|0, (3<<3)|1, (2<<3)|0, (5<<3)|1
    !byte (7<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2
    !byte (3<<3)|1, (2<<3)|0, (3<<3)|1, (2<<3)|0, (2<<3)|1, (10<<3)|0, (1<<3)|2, (31<<3)|0
    !byte (17<<3)|0, (14<<3)|1, (2<<3)|0, (8<<3)|1

; --- pickup ---
; screen $10d9 x=1 y=9
    !word $10d9

; --- ramp ---
; x=13 y=11 len=7 dir=0
    !byte $6b, $0d

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; razor: x=16 y=32 min=16 max=104 vel=2 WHT vertical set=36
    !byte 16, 32, 16, 104, 2, WHT, 1, 36
; barrel: x=36 y=16 min=16 max=48 vel=1 RED vertical set=22
    !byte 36, 16, 16, 48, 1, RED, 1, 22
; multitool: x=48 y=104 min=40 max=87 vel=1 CYN horizontal set=37
    !byte 48, 104, 40, 87, 1, CYN, 0, 37
