; room 57 — Above W Bedroom
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room57_data
; --- title ---
; "Above W Bedroom"
    !pet "Above W Bedroom", 0

; --- meta8 ---
; conn N E S W
    !byte 0, 56, 55, 0
; spawn px py
    !byte 68, 104
; flags: nasty|ramp
    !byte FLAG_NASTY|FLAG_RAMP
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, WHT, YEL, WHT, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 17
; wall
    !byte 10
; pickup
    !byte 10
; nasty
    !byte 3
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 41 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (10<<3)|0, (3<<3)|1, (20<<3)|0
    !byte (1<<3)|3, (1<<3)|1, (21<<3)|0, (1<<3)|3, (1<<3)|0, (1<<3)|1, (20<<3)|0, (1<<3)|3
    !byte (2<<3)|0, (1<<3)|1, (19<<3)|0, (1<<3)|3, (3<<3)|0, (1<<3)|1, (18<<3)|0, (8<<3)|1
    !byte (9<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|3, (14<<3)|0, (1<<3)|1, (7<<3)|0, (1<<3)|3
    !byte (21<<3)|0, (2<<3)|2, (15<<3)|0, (1<<3)|1, (6<<3)|0, (2<<3)|2, (2<<3)|0, (5<<3)|1
    !byte (3<<3)|0

; --- pickup ---
    !word screen_base + 235

; --- ramp ---
; x=13 y=13 len=8 dir=0
    !byte $7d, $0d

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; clive: x=28 y=50 min=15 max=80 vel=-5 CYN vertical set=18
    !byte 28, 50, 15, 80, 251, CYN, 1, 18
; jelly: x=40 y=24 min=0 max=80 vel=1 RED vertical set=41
    !byte 40, 24, 0, 80, 1, RED, 1, 41
