; room 35 — Master Bedroom
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room35_data
; --- title ---
; "Master Bedroom"
    !pet "Master Bedroom", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 34, 255, 255
; spawn px py
    !byte 44, 16
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border PUR, background BLK; (bg<<4)|border = 4 (byte $0c includes VIC bit 3)
    !byte 12

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, PUR, WHT, YEL, CYN

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $6b, $b5, $00, $ad, $00, $4a, $00
; wall
    !byte $ff, $ae, $04, $ae, $ff, $55, $40, $55
; pickup
    !byte $00, $00, $00, $00, $00, $00, $00, $00
; nasty
    !byte $00, $00, $00, $00, $7c, $fe, $7f, $3e
; ramp
    !byte $c0, $40, $b0, $00, $ac, $00, $53, $00
; belt
    !byte $55, $55, $55, $55, $51, $5f, $40, $aa

; --- rle_tilemap ---
; 52 tokens, 384 cells — each byte (N<<3)|C
    !byte (26<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (1<<3)|3, (21<<3)|0, (2<<3)|2, (22<<3)|0, (1<<3)|2, (12<<3)|1, (11<<3)|0
    !byte (14<<3)|2, (10<<3)|0, (15<<3)|2, (9<<3)|1

; --- pickup ---
; no pickup
    !word $ffff

; --- ramp ---
; x=13 y=13 len=2 dir=0
    !byte $ad, $85, $00

; --- conveyor ---
; x=2 y=12 len=3 belt=0
    !byte $82, $07, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; maria: x=40 y=88 min=88 max=88 vel=0 WHT vertical set=30
    !byte 40, 88, 88, 88, 0, WHT, 1, 30
