; room 42 — Under the Roof
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room42_data
; --- title ---
; "Under the Roof"
    !byte 21, 36, 27, 28, 39, 56, 41, 31, 28, 56, 18, 37, 37, 29, 0

; --- meta8 ---
; conn N E S W
    !byte 48, 41, 36, 43
; spawn px py
    !byte 68, 104
; flags: nasty|ramp|conveyor|arrow
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR|FLAG_ARROW
; border RED, background BLU; (bg<<4)|border = 98 (byte $6a includes VIC bit 3)
    !byte 106

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, CYN, WHT, YEL

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $b5, $aa, $55, $4a, $25, $42, $01, $02
; wall
    !byte $66, $b6, $6d, $bb, $66, $b9, $6d, $b6
; pickup
    !byte $3e, $7f, $53, $53, $3e, $2a, $16, $3c
; nasty
    !byte $99, $55, $a0, $43, $9c, $53, $94, $5b
; ramp
    !byte $01, $02, $04, $28, $10, $28, $40, $80
; belt
    !byte $a5, $aa, $bd, $66, $66, $66, $66, $66

; --- rle_tilemap ---
; 50 tokens, 384 cells — each byte (N<<3)|C
    !byte (8<<3)|0, (15<<3)|3, (12<<3)|0, (1<<3)|3, (2<<3)|0, (3<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (14<<3)|0, (3<<3)|3, (1<<3)|0, (3<<3)|3, (1<<3)|0, (3<<3)|3, (18<<3)|0, (1<<3)|3
    !byte (31<<3)|0, (31<<3)|0, (18<<3)|0, (3<<3)|2, (2<<3)|1, (31<<3)|0, (31<<3)|0, (31<<3)|0
    !byte (8<<3)|0, (2<<3)|2, (6<<3)|0, (1<<3)|1, (11<<3)|0, (2<<3)|1, (2<<3)|0, (2<<3)|2
    !byte (4<<3)|0, (1<<3)|1, (7<<3)|0, (4<<3)|1, (6<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1
    !byte (9<<3)|0, (2<<3)|1, (7<<3)|0, (1<<3)|1, (2<<3)|2, (22<<3)|0, (2<<3)|2, (5<<3)|0
    !byte (1<<3)|1, (6<<3)|0

; --- pickup ---
; screen $10ba x=18 y=7
    !word $10ba

; --- ramp ---
; x=2 y=6 len=6 dir=0
    !byte $56, $02

; --- conveyor ---
; x=8 y=6 len=16 belt=1
    !byte $f6, $88

; --- arrow ---
; x=80 y=97 v=1 sound=115
    !byte $61, $50, $03, $73, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; cone: x=12 y=72 min=0 max=23 vel=1 WHT horizontal set=28
    !byte 12, 72, 0, 23, 1, WHT, 0, 28
; multitool: x=40 y=64 min=40 max=63 vel=1 CYN horizontal set=37
    !byte 40, 64, 40, 63, 1, CYN, 0, 37
