; room 18 — On the Roof
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room18_data
; --- title ---
; "On the Roof"
    !byte 15, 40, 63, 46, 34, 31, 63, 18, 41, 41, 32, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 17, 0, 48
; spawn px py
    !byte 1, 56
; flags: nasty|conveyor|rope
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ROPE
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, WHT, GRN, YEL, WHT, PUR

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 14
; wall
    !byte 0
; pickup
    !byte 4
; nasty
    !byte 11
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 38 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (1<<3)|0, (2<<3)|2
    !byte (1<<3)|1, (21<<3)|0, (2<<3)|2, (1<<3)|3, (1<<3)|1, (1<<3)|0, (4<<3)|2, (1<<3)|1
    !byte (14<<3)|0, (9<<3)|2, (1<<3)|3, (14<<3)|0, (9<<3)|2, (1<<3)|3, (14<<3)|0, (10<<3)|2
    !byte (1<<3)|1, (13<<3)|0, (10<<3)|2, (1<<3)|3, (13<<3)|0, (10<<3)|2, (1<<3)|3, (2<<3)|0
    !byte (2<<3)|2, (1<<3)|1, (8<<3)|0, (17<<3)|2, (5<<3)|0, (7<<3)|2

; --- pickup ---
; screen $1132 x=18 y=12
    !word $1132

; --- conveyor ---
; x=12 y=15 len=5 belt=1
    !byte $4f, $8c

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 1
; rabbit: x=72 y=104 min=44 max=71 vel=-1 CYN horizontal set=5
    !byte 72, 104, 44, 71, 255, CYN, 0, 5
