; room 13 — Out on a limb
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room13_data
; --- title ---
; "Out on a limb"
    !byte 15, 42, 41, 56, 37, 36, 56, 24, 56, 34, 32, 35, 25, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 12, 9, 10
; spawn px py
    !byte 88, 80
; flags: nasty
    !byte FLAG_NASTY
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, RED, GRN, WHT

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 12
; wall
    !byte 11
; pickup
    !byte 12
; nasty
    !byte 5
; ramp
    !byte 0
; belt
    !byte 0

; --- rle_tilemap ---
; 52 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (6<<3)|0, (1<<3)|1, (16<<3)|0, (1<<3)|1
    !byte (9<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1, (12<<3)|0, (1<<3)|1, (31<<3)|0, (5<<3)|0
    !byte (1<<3)|1, (19<<3)|0, (1<<3)|1, (9<<3)|0, (1<<3)|1, (9<<3)|0, (1<<3)|1, (16<<3)|0
    !byte (1<<3)|1, (5<<3)|0, (1<<3)|1, (1<<3)|0, (1<<3)|1, (18<<3)|0, (1<<3)|1, (3<<3)|0
    !byte (1<<3)|1, (1<<3)|0, (11<<3)|2, (2<<3)|0, (1<<3)|1, (11<<3)|0, (1<<3)|1, (6<<3)|3
    !byte (8<<3)|0, (1<<3)|1, (5<<3)|0, (1<<3)|1, (3<<3)|0, (1<<3)|1, (4<<3)|3, (12<<3)|0
    !byte (1<<3)|1, (8<<3)|0, (2<<3)|1, (5<<3)|0

; --- pickup ---
; screen $101b x=3 y=1
    !word $101b

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; pinhead: x=32 y=88 min=0 max=104 vel=4 CYN vertical set=2
    !byte 32, 88, 0, 104, 4, CYN, 1, 2
; saw: x=60 y=80 min=56 max=87 vel=-1 YEL horizontal set=8
    !byte 60, 80, 56, 87, 255, YEL, 0, 8
