; room 30 — The Banyan Tree
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room30_data
; --- title ---
; "The Banyan Tree"
    !pet "The Banyan Tree", 0

; --- meta8 ---
; conn N E S W
    !byte 36, 29, 255, 31
; spawn px py
    !byte 8, 16
; flags: ramp
    !byte FLAG_RAMP
; border PUR, background BLK; (bg<<4)|border = 4 (byte $0c includes VIC bit 3)
    !byte 12

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, BLU, RED, BLK, YEL, BLK

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $5d, $ff, $ff, $ff, $b9, $ff, $6c
; wall
    !byte $b5, $d6, $da, $b6, $6d, $5b, $da, $6b
; pickup
    !byte $05, $38, $45, $82, $82, $82, $44, $38
; ramp
    !byte $03, $00, $0c, $00, $30, $00, $c0, $00

; --- rle_tilemap ---
; 60 tokens, 384 cells — each byte (N<<3)|C
    !byte (10<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (1<<3)|2, (1<<3)|1, (22<<3)|0
    !byte (1<<3)|2, (2<<3)|1, (21<<3)|0, (6<<3)|1, (21<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1
    !byte (20<<3)|0, (1<<3)|1, (2<<3)|0, (1<<3)|1, (23<<3)|0, (1<<3)|1, (17<<3)|0, (1<<3)|2
    !byte (23<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (14<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (11<<3)|0, (1<<3)|2
    !byte (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2, (2<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (19<<3)|2, (2<<3)|1, (8<<3)|2, (14<<3)|0, (2<<3)|1, (8<<3)|2, (14<<3)|0
    !byte (2<<3)|1, (8<<3)|2, (16<<3)|1, (3<<3)|2

; --- pickup ---
    !word screen_base + 341

; --- ramp ---
; x=2 y=11 len=8 dir=0
    !byte $62, $91, $01

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; spiral: x=32 y=64 min=56 max=80 vel=-1 GRN vertical set=32
    !byte 32, 64, 56, 80, 255, GRN, 1, 32
; elf: x=44 y=48 min=40 max=80 vel=2 PUR vertical set=33
    !byte 44, 48, 40, 80, 2, PUR, 1, 33
; chip: x=56 y=76 min=40 max=80 vel=1 CYN vertical set=34
    !byte 56, 76, 40, 80, 1, CYN, 1, 34
; saw: x=72 y=80 min=68 max=91 vel=-1 YEL horizontal set=8
    !byte 72, 80, 68, 91, 255, YEL, 0, 8
