; room 08 — Inside MegaTrunk
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room08_data
; --- title ---
; "Inside MegaTrunk"
    !pet "Inside MegaTrunk", 0

; --- meta8 ---
; conn N E S W
    !byte 12, 7, 3, 9
; spawn px py
    !byte 48, 104
; flags: nasty|ramp
    !byte FLAG_NASTY|FLAG_RAMP
; border GRN, background BLK; (bg<<4)|border = 5 (byte $0d includes VIC bit 3)
    !byte 13

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, RED, YEL, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $f5, $fa, $bf, $1f, $26, $14, $22, $10
; wall
    !byte $ab, $ab, $ad, $aa, $aa, $ae, $55, $55
; pickup
    !byte $12, $24, $28, $28, $7c, $ae, $ac, $78
; nasty
    !byte $6e, $74, $38, $1e, $6e, $74, $38, $1e
; ramp
    !byte $40, $00, $10, $00, $04, $00, $01, $00

; --- rle_tilemap ---
; 92 tokens, 384 cells — each byte (N<<3)|C
    !byte (7<<3)|0, (1<<3)|2, (7<<3)|0, (1<<3)|2, (15<<3)|0, (1<<3)|2, (7<<3)|0, (1<<3)|2
    !byte (15<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (4<<3)|0, (2<<3)|1, (17<<3)|0, (2<<3)|1
    !byte (29<<3)|0, (1<<3)|1, (5<<3)|2, (15<<3)|0, (2<<3)|1, (2<<3)|0, (1<<3)|2, (8<<3)|0
    !byte (8<<3)|2, (7<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|2, (1<<3)|1, (6<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (2<<3)|0, (1<<3)|2, (4<<3)|0, (3<<3)|1, (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|3, (2<<3)|0, (1<<3)|2, (17<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|2, (3<<3)|0, (2<<3)|1, (12<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0
    !byte (1<<3)|2, (17<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (6<<3)|0, (9<<3)|2, (1<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (7<<3)|0, (1<<3)|2, (9<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|2
    !byte (4<<3)|0, (3<<3)|1, (1<<3)|2, (8<<3)|0

; --- pickup ---
    !word screen_base + 190

; --- ramp ---
; x=20 y=5 len=2 dir=0
    !byte $b4, $84, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; pinhead: x=36 y=32 min=0 max=104 vel=2 RED vertical set=2
    !byte 36, 32, 0, 104, 2, RED, 1, 2
; bird: x=24 y=40 min=0 max=31 vel=-1 CYN horizontal set=3
    !byte 24, 40, 0, 31, 255, CYN, 0, 3
; bird: x=76 y=88 min=52 max=91 vel=-1 GRN horizontal set=3
    !byte 76, 88, 52, 91, 255, GRN, 0, 3
; flower: x=72 y=24 min=56 max=91 vel=-1 YEL horizontal set=14
    !byte 72, 24, 56, 91, 255, YEL, 0, 14
