; room 21 — Ballroom West
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room21_data
; --- title ---
; "Ballroom West"
    !byte 2, 24, 34, 34, 39, 37, 37, 35, 56, 22, 28, 40, 41, 0

; --- meta8 ---
; conn N E S W
    !byte 255, 20, 255, 22
; spawn px py
    !byte 0, 96
; flags: ramp|conveyor
    !byte FLAG_RAMP|FLAG_CONVEYOR
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, GRN, PUR, WHT, YEL

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 9
; wall
    !byte 15
; pickup
    !byte 7
; nasty
    !byte 0
; ramp
    !byte 1
; belt
    !byte 5

; --- rle_tilemap ---
; 28 tokens, 384 cells — each byte (N<<3)|C
    !byte (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (31<<3)|0, (17<<3)|0
    !byte (24<<3)|1, (6<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (10<<3)|0
    !byte (6<<3)|1, (6<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (31<<3)|0
    !byte (31<<3)|0, (2<<3)|0, (24<<3)|1, (24<<3)|2

; --- pickup ---
; screen $10fe x=14 y=10
    !word $10fe

; --- ramp ---
; x=0 y=11 len=3 dir=0
    !byte $2b, $00

; --- conveyor ---
; x=11 y=13 len=10 belt=1
    !byte $9d, $8b

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 3
; rabbit: x=72 y=88 min=48 max=75 vel=-1 PUR horizontal set=5
    !byte 72, 88, 48, 75, 255, PUR, 0, 5
; pinhead: x=36 y=56 min=48 max=96 vel=2 CYN vertical set=2
    !byte 36, 56, 48, 96, 2, CYN, 1, 2
; pinhead: x=16 y=72 min=48 max=87 vel=-3 PUR vertical set=2
    !byte 16, 72, 48, 87, 253, PUR, 1, 2
