; room 26 — East Wall Base
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room26_data
; --- title ---
; "East Wall Base"
    !byte 5, 24, 40, 41, 56, 22, 24, 34, 34, 56, 2, 24, 40, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 32, 255, 20, 255
; spawn px py
    !byte 16, 104
; flags: none
    !byte 0
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, GRN, WHT, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $5b, $a4, $a4, $55, $0a, $00, $00, $00
; wall
    !byte $59, $25, $26, $d9, $29, $d6, $54, $96
; pickup
    !byte $18, $34, $34, $5a, $5a, $bf, $a1, $7e

; --- rle_tilemap ---
; 74 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1
    !byte (3<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (1<<3)|1, (7<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1, (17<<3)|0
    !byte (2<<3)|2, (22<<3)|0, (2<<3)|2, (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (3<<3)|0, (1<<3)|1, (4<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (2<<3)|2, (4<<3)|0, (1<<3)|1, (3<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (7<<3)|0, (1<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0
    !byte (2<<3)|2, (12<<3)|0

; --- pickup ---
; screen $1111 x=9 y=11
    !word $1111

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; scroll: x=12 y=72 min=0 max=96 vel=-2 RED vertical set=29
    !byte 12, 72, 0, 96, 254, RED, 1, 29
; pinhead: x=28 y=88 min=0 max=104 vel=4 CYN vertical set=2
    !byte 28, 88, 0, 104, 4, CYN, 1, 2
