; room 60 — The Bow
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room60_data
; --- title ---
; "The Bow"
    !pet "The Bow", 0

; --- meta8 ---
; conn N E S W
    !byte 255, 59, 255, 255
; spawn px py
    !byte 44, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border CYN, background BLK; (bg<<4)|border = 3 (byte $0b includes VIC bit 3)
    !byte 11

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, GRN, CYN, BLU, WHT, YEL

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 7
; wall
    !byte 1
; pickup
    !byte 1
; nasty
    !byte 4
; ramp
    !byte 1
; belt
    !byte 2

; --- rle_tilemap ---
; 25 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (31<<3)|0, (11<<3)|0, (9<<3)|1, (16<<3)|0, (1<<3)|2
    !byte (18<<3)|0, (1<<3)|1, (4<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (1<<3)|1, (22<<3)|0
    !byte (1<<3)|2, (14<<3)|0, (17<<3)|1, (31<<3)|0, (31<<3)|0, (31<<3)|0, (3<<3)|0, (11<<3)|3
    !byte (13<<3)|0

; --- pickup ---
    !word screen_base + 210

; --- ramp ---
; x=5 y=9 len=6 dir=0
    !byte $59, $05

; --- conveyor ---
; x=11 y=15 len=13 belt=1
    !byte $cf, $8b

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 2
; hootbot: x=68 y=24 min=64 max=87 vel=-1 YEL horizontal set=1
    !byte 68, 24, 64, 87, 255, YEL, 0, 1
; wirecutter: x=48 y=104 min=44 max=87 vel=-1 PUR horizontal set=23
    !byte 48, 104, 44, 87, 255, PUR, 0, 23
