; room 38 — Priests' Hole
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room38_data
; --- title ---
; "Priests' Hole"
    !byte 16, 39, 32, 28, 40, 41, 40, 57, 56, 8, 37, 34, 28, 0

; --- meta8 ---
; conn N E S W
    !byte 60, 255, 32, 39
; spawn px py
    !byte 30, 104
; flags: none
    !byte 0
; border RED, background BLK; (bg<<4)|border = 2 (byte $0a includes VIC bit 3)
    !byte 10

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, CYN, WHT, WHT, WHT

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $55, $55, $5d, $d7, $70, $00, $00, $00
; wall
    !byte $dd, $ee, $bb, $77, $dd, $ee, $bb, $77
; pickup
    !byte $bf, $bf, $bb, $b1, $bb, $bb, $bf, $bf

; --- rle_tilemap ---
; 69 tokens, 384 cells — each byte (N<<3)|C
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (8<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (22<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (3<<3)|1, (3<<3)|0, (2<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0
    !byte (2<<3)|2, (12<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0, (2<<3)|2, (12<<3)|0
    !byte (2<<3)|2, (6<<3)|0, (1<<3)|1, (1<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0
    !byte (2<<3)|2, (12<<3)|0, (2<<3)|2, (1<<3)|0, (2<<3)|1, (19<<3)|0, (2<<3)|2, (22<<3)|0
    !byte (2<<3)|2, (6<<3)|0, (2<<3)|1, (2<<3)|2, (12<<3)|0, (2<<3)|2, (8<<3)|0, (2<<3)|2
    !byte (12<<3)|0, (2<<3)|2, (2<<3)|0, (1<<3)|1, (5<<3)|0, (2<<3)|2, (12<<3)|0, (2<<3)|2
    !byte (5<<3)|0, (1<<3)|1, (2<<3)|0, (2<<3)|2, (12<<3)|0

; --- pickup ---
; screen $1039 x=9 y=2
    !word $1039

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; demonc: x=24 y=64 min=16 max=104 vel=1 GRN vertical set=11
    !byte 24, 64, 16, 104, 1, GRN, 1, 11
; demona: x=20 y=48 min=0 max=88 vel=1 GRN vertical set=12
    !byte 20, 48, 0, 88, 1, GRN, 1, 12
; demonb: x=24 y=48 min=0 max=88 vel=1 GRN vertical set=13
    !byte 24, 48, 0, 88, 1, GRN, 1, 13
; bird: x=56 y=80 min=32 max=63 vel=-1 RED horizontal set=3
    !byte 56, 80, 32, 63, 255, RED, 0, 3
