; room 41 — The Attic
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room41_data
; --- title ---
; "The Attic"
    !byte 20, 34, 31, 63, 1, 46, 46, 35, 29, 0

; --- meta8 ---
; conn N E S W
    !byte 0, 40, 34, 42
; spawn px py
    !byte 90, 48
; flags: nasty|conveyor|arrow
    !byte FLAG_NASTY|FLAG_CONVEYOR|FLAG_ARROW
; border BLU, background BLK; (bg<<4)|border = 6 (byte $0e includes VIC bit 3)
    !byte 14

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, YEL, PUR, GRN, WHT, RED

; --- tile_udg ---
; canonical pool indices: floor wall pickup nasty ramp belt (6 B)
; type 0 empty is always zero — not stored
; floor
    !byte 3
; wall
    !byte 4
; pickup
    !byte 19
; nasty
    !byte 0
; ramp
    !byte 0
; belt
    !byte 3

; --- rle_tilemap ---
; 62 tokens, 384 cells — each byte (N<<3)|C
    !byte (31<<3)|0, (31<<3)|0, (31<<3)|0, (30<<3)|0, (1<<3)|3, (4<<3)|0, (1<<3)|3, (15<<3)|0
    !byte (3<<3)|1, (1<<3)|2, (4<<3)|1, (1<<3)|2, (2<<3)|1, (13<<3)|0, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (1<<3)|1, (11<<3)|0, (1<<3)|1, (9<<3)|0, (1<<3)|1, (1<<3)|2, (23<<3)|0
    !byte (1<<3)|2, (1<<3)|1, (13<<3)|0, (1<<3)|1, (8<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2
    !byte (1<<3)|1, (15<<3)|0, (1<<3)|1, (6<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (1<<3)|1
    !byte (3<<3)|0, (1<<3)|3, (3<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3, (2<<3)|0, (1<<3)|3
    !byte (4<<3)|0, (1<<3)|3, (3<<3)|0, (5<<3)|1, (1<<3)|2, (3<<3)|1, (1<<3)|2, (2<<3)|1
    !byte (1<<3)|2, (2<<3)|1, (1<<3)|2, (4<<3)|1, (1<<3)|2, (3<<3)|1

; --- pickup ---
; screen $1153 x=3 y=14
    !word $1153

; --- conveyor ---
; x=18 y=8 len=3 belt=1
    !byte $28, $92

; --- arrow ---
; x=22 y=41 v=-1 sound=36
    !byte $29, $16, $01, $24, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 4
; pacbody: x=12 y=66 min=56 max=88 vel=2 PUR vertical set=38
    !byte 12, 66, 56, 88, 2, PUR, 1, 38
; pacbody: x=20 y=70 min=56 max=88 vel=2 YEL vertical set=38
    !byte 20, 70, 56, 88, 2, YEL, 1, 38
; pacbody: x=28 y=74 min=56 max=88 vel=2 BLU vertical set=38
    !byte 28, 74, 56, 88, 2, BLU, 1, 38
; pachead: x=36 y=78 min=56 max=88 vel=2 CYN vertical set=21
    !byte 36, 78, 56, 88, 2, CYN, 1, 21
