; room 22 — Main Stairway
; Generated by mkcatalogue.py — do not edit.

!source "bake/room_record.asm"
!source "bake/vic_colors.asm"

room22_data
; --- title ---
; "Main Stairway"
    !pet "Main Stairway", 0

; --- meta8 ---
; conn N E S W
    !byte 28, 21, 0, 23
; spawn px py
    !byte 44, 104
; flags: nasty|ramp|conveyor
    !byte FLAG_NASTY|FLAG_RAMP|FLAG_CONVEYOR
; border GRN, background BLU; (bg<<4)|border = 101 (byte $6d includes VIC bit 3)
    !byte 109

; --- tile_colors ---
; types 0-5: empty floor wall nasty ramp belt
    !byte WHT, CYN, RED, CYN, WHT, PUR

; --- tile_udg ---
; types 1 floor, 2 wall, 6 pickup always; 3 nasty / 4 ramp / 5 belt when flagged
; type 0 empty is always zero — not stored
; floor
    !byte $ff, $ff, $00, $ff, $00, $00, $00, $00
; wall
    !byte $ff, $ea, $40, $ea, $ff, $ae, $04, $ae
; pickup
    !byte $40, $a0, $f0, $f8, $fc, $7a, $25, $02
; nasty
    !byte $18, $5a, $bd, $19, $7e, $99, $24, $24
; ramp
    !byte $c0, $80, $30, $20, $0c, $08, $03, $02
; belt
    !byte $f0, $aa, $78, $ff, $aa, $55, $aa, $55

; --- rle_tilemap ---
; 42 tokens, 384 cells — each byte (N<<3)|C
    !byte (4<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (23<<3)|0, (1<<3)|2, (14<<3)|0, (1<<3)|3
    !byte (31<<3)|0, (24<<3)|0, (1<<3)|1, (1<<3)|2, (11<<3)|1, (4<<3)|0, (4<<3)|1, (4<<3)|0
    !byte (1<<3)|2, (23<<3)|0, (1<<3)|2, (19<<3)|0, (2<<3)|2, (2<<3)|1, (1<<3)|2, (1<<3)|0
    !byte (2<<3)|1, (16<<3)|0, (1<<3)|2, (3<<3)|0, (1<<3)|2, (11<<3)|0, (5<<3)|1, (3<<3)|0
    !byte (1<<3)|2, (3<<3)|0, (1<<3)|2, (8<<3)|0, (2<<3)|1, (31<<3)|0, (31<<3)|0, (19<<3)|0
    !byte (31<<3)|2, (17<<3)|2

; --- pickup ---
    !word screen_base + 149

; --- ramp ---
; x=12 y=0 len=12 dir=0
    !byte $0c, $98, $00

; --- conveyor ---
; x=10 y=8 len=2 belt=-1
    !byte $0a, $45, $00

; --- guardians ---
; count, then 8 B per guardian:
;   x, y, min, max, vel, color, axis (0=horizontal 1=vertical), set_idx
    !byte 6
; wirecutter: x=8 y=24 min=0 max=27 vel=1 PUR horizontal set=23
    !byte 8, 24, 0, 27, 1, PUR, 0, 23
; hootbot: x=48 y=24 min=36 max=55 vel=-1 YEL horizontal set=1
    !byte 48, 24, 36, 55, 255, YEL, 0, 1
; tambourine: x=64 y=48 min=32 max=63 vel=-1 WHT horizontal set=24
    !byte 64, 48, 32, 63, 255, WHT, 0, 24
; globes: x=8 y=72 min=4 max=11 vel=1 RED horizontal set=25
    !byte 8, 72, 4, 11, 1, RED, 0, 25
; bird: x=28 y=80 min=20 max=47 vel=-1 YEL horizontal set=3
    !byte 28, 80, 20, 47, 255, YEL, 0, 3
; egg: x=64 y=96 min=0 max=91 vel=-1 GRN horizontal set=9
    !byte 64, 96, 0, 91, 255, GRN, 0, 9
