#!/usr/bin/env python3
"""Build bake/fontchars.asm subset and bake/font_subset.json from room titles."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))

from font_glyph import (  # noqa: E402
    FULL_GLYPH_CHARS,
    FULL_GLYPH_COUNT,
    ascii_to_full_glyph,
    parse_fontchars_asm,
    titles_glyph_set,
)
from title_strings import load_title_lines  # noqa: E402


def title_screen_glyph_set() -> set[int]:
    used: set[int] = set()
    for line in load_title_lines():
        for ch in line:
            used.add(ascii_to_full_glyph(ch))
    return used

FULL_FONT_ASM = Path(__file__).resolve().parent / "fontchars_full.asm"
BAKE_FONT = ROOT / "bake" / "fontchars.asm"
BAKE_SUBSET = ROOT / "bake" / "font_subset.json"
BAKE_EQUATES = ROOT / "bake" / "font_equates.inc"
DIGIT_FULL_START = 52
DIGIT_FULL_END = 61


def subset_full_indices(rooms_dir: Path) -> list[int]:
    used = titles_glyph_set(rooms_dir) | title_screen_glyph_set()
    keep = used | set(range(DIGIT_FULL_START, DIGIT_FULL_END + 1))
    return sorted(keep)


def format_fontchars_asm(full_rows: list[list[int]], full_indices: list[int]) -> str:
    lines = [
        "; Generated by tools/export_font_asm.py — do not edit.",
        f"; {len(full_indices)} glyphs ({len(full_indices) * 8} B), subset of {FULL_GLYPH_COUNT} in fontchars_full.asm",
        "",
        "!zone fontchars",
        "",
    ]
    for full_idx in full_indices:
        row = full_rows[full_idx]
        label = FULL_GLYPH_CHARS[full_idx]
        hexes = ", ".join(str(b) for b in row)
        lines.append(f"        ; full {full_idx:2d} {label!r}")
        lines.append(f"        !byte {hexes}")
    return "\n".join(lines) + "\n"


def compact_digit_map(full_indices: list[int]) -> dict[str, int]:
    full_to_compact = {full: compact for compact, full in enumerate(full_indices)}
    out: dict[str, int] = {}
    for d, full in enumerate(range(DIGIT_FULL_START, DIGIT_FULL_END + 1)):
        out[str(d)] = full_to_compact[full]
    return out


def assert_sequential_digits(digit_compact: dict[str, int]) -> int:
    """Return compact index of digit 0; require digits 0-9 at consecutive slots."""
    values = [digit_compact[str(d)] for d in range(10)]
    if values != list(range(values[0], values[0] + 10)):
        raise SystemExit(f"digit_compact not sequential: {values}")
    return values[0]


def write_font_equates_inc(glyph_count: int, digit_compact_0: int) -> None:
    lines = [
        "; Generated by tools/export_font_asm.py — do not edit.",
        f"FONT_GLYPH_COUNT = {glyph_count}",
        f"DIGIT_COMPACT_0 = {digit_compact_0}",
        "DIGIT_0_CHR = FONT_CHR + DIGIT_COMPACT_0",
        "",
    ]
    BAKE_EQUATES.write_text("\n".join(lines), encoding="utf-8")


def write_subset_json(full_indices: list[int], rooms_dir: Path) -> None:
    full_to_compact = {str(full): compact for compact, full in enumerate(full_indices)}
    compact_labels = [FULL_GLYPH_CHARS[full] for full in full_indices]
    dropped = sorted(set(range(FULL_GLYPH_COUNT)) - set(full_indices))
    payload = {
        "glyph_count": len(full_indices),
        "full_indices": full_indices,
        "compact_labels": compact_labels,
        "full_to_compact": full_to_compact,
        "digit_compact": compact_digit_map(full_indices),
        "dropped_full_indices": dropped,
        "dropped_labels": [FULL_GLYPH_CHARS[i] for i in dropped],
        "bytes_saved": (FULL_GLYPH_COUNT - len(full_indices)) * 8,
        "rooms_scanned": str(rooms_dir),
    }
    BAKE_SUBSET.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export proportional font subset")
    parser.add_argument("--rooms", type=Path, default=ROOT / "rooms")
    args = parser.parse_args()

    full_rows = parse_fontchars_asm(FULL_FONT_ASM)
    if len(full_rows) != FULL_GLYPH_COUNT:
        raise SystemExit(f"expected {FULL_GLYPH_COUNT} glyphs in {FULL_FONT_ASM}, got {len(full_rows)}")

    full_indices = subset_full_indices(args.rooms)
    saved = (FULL_GLYPH_COUNT - len(full_indices)) * 8

    BAKE_FONT.write_text(format_fontchars_asm(full_rows, full_indices), encoding="utf-8")
    write_subset_json(full_indices, args.rooms)
    digit_map = compact_digit_map(full_indices)
    digit_compact_0 = assert_sequential_digits(digit_map)
    write_font_equates_inc(len(full_indices), digit_compact_0)

    print(f"Wrote {BAKE_FONT.relative_to(ROOT)} ({len(full_indices)} glyphs, {len(full_indices) * 8} B)")
    print(f"Wrote {BAKE_SUBSET.relative_to(ROOT)}")
    print(f"Wrote {BAKE_EQUATES.relative_to(ROOT)}")
    print(f"Dropped {FULL_GLYPH_COUNT - len(full_indices)} glyphs, saved {saved} B")
    print(f"Digit compact indices 0-9: {digit_map}")


if __name__ == "__main__":
    main()
