#!/usr/bin/env python3
"""Emit bake/title_strings.inc from title_strings.txt."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from font_glyph import pack_title_glyphs  # noqa: E402
from title_strings import load_title_lines  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "bake" / "title_strings.inc"


def main() -> None:
    title_lines = load_title_lines()
    lines = [
        "; Generated by tools/gen_title_strings.py from title_strings.txt — do not edit.",
        "",
    ]
    for i, text in enumerate(title_lines):
        data = pack_title_glyphs(text)
        hexes = ", ".join(f"${b:02x}" for b in data)
        label = "title_text" if i == 0 else f"title_line{i}"
        lines.append(label)
        lines.append(f"    !byte {hexes}")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(OUT.parent.parent)} ({len(title_lines)} lines)")


if __name__ == "__main__":
    main()
