#!/usr/bin/env python3
"""Build loadram_test.d64: harness PRG + TST payload (512 B @ $1C00-$1DFF)."""

from __future__ import annotations

import argparse
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_VICE = Path(r"c:\app\vice3.10\bin")
LOAD_ADDR = 0x1C00
PAYLOAD_SIZE = 512


def payload_bytes() -> bytes:
    """Distinct from $55/$AA canaries: nybble counter in high nibble."""
    return bytes((i & 0x0F) | 0xE0 for i in range(PAYLOAD_SIZE))


def write_payload_inc(path: Path, data: bytes) -> None:
    lines = [
        "; Auto-generated by mkloadram_test.py — expected LOAD payload @ $1C00 (512 B)",
        "",
        "load_payload_expected:",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    !byte " + ", ".join(f"${b:02x}" for b in chunk))
    lines.append(f"load_payload_size = {len(data)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_prg(path: Path, data: bytes, load_addr: int = LOAD_ADDR) -> None:
    path.write_bytes(struct.pack("<H", load_addr) + data)


def find_c1541() -> Path | None:
    for base in (DEFAULT_VICE, Path("/usr/bin")):
        for name in ("c1541.exe", "c1541"):
            p = base / name
            if p.is_file():
                return p
    return None


def build_d64(d64: Path, harness: Path, tst: Path, c1541: Path) -> None:
    if d64.exists():
        d64.unlink()
    subprocess.check_call(
        [
            str(c1541),
            "-format",
            "loadram,01",
            "d64",
            str(d64),
            "-attach",
            str(d64),
            "-write",
            str(harness),
            "test",
            "-write",
            str(tst),
            "tst,p",
        ]
    )
    print(f"Wrote {d64}")


def write_payload_artifacts(inc: Path, tst: Path) -> bytes:
    data = payload_bytes()
    write_payload_inc(inc, data)
    write_prg(tst, data)
    print(f"Payload {len(data)} bytes @ ${LOAD_ADDR:04X}-${LOAD_ADDR + len(data) - 1:04X}")
    print(f"  -> {tst.name}, {inc.name}")
    return data


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inc", type=Path, default=ROOT / "loadram_payload.inc")
    parser.add_argument("--tst", type=Path, default=ROOT / "loadram_tst.prg")
    parser.add_argument("--d64", type=Path, default=ROOT / "loadram_test.d64")
    parser.add_argument("--harness", type=Path, default=ROOT / "loadram_test.prg")
    parser.add_argument(
        "--payload-only",
        action="store_true",
        help="write loadram_payload.inc and loadram_tst.prg only",
    )
    args = parser.parse_args()

    write_payload_artifacts(args.inc, args.tst)
    if args.payload_only:
        return 0

    if not args.harness.is_file():
        print(f"error: build {args.harness} first (make_loadram_test.bat)", file=sys.stderr)
        return 1

    c1541 = find_c1541()
    if c1541 is None:
        print("warning: c1541 not found — inc/tst written; build D64 manually", file=sys.stderr)
        return 0

    build_d64(args.d64, args.harness, args.tst, c1541)
    return 0


if __name__ == "__main__":
    sys.exit(main())
