#!/usr/bin/env python3
"""Export Spectrum JSW rope animation table as 86 nybble-packed bytes.

Each byte: high nybble = rotate count, low nybble = y-offset step.
Index I is used by segment S at frame F via table[F + S] (F & 127).
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

# Spectrum disassembly at 33536 (rotate) and 33664 (yoff), indices 0-85.
ROPE_ROTATE = [
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 1, 2, 2, 1, 1, 2,
    1, 1, 2, 2, 3, 2, 3, 2,
    3, 3, 3, 3, 3, 3,
]

ROPE_YOFF = [
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6,
    4, 6, 6, 4, 6, 4, 6, 4,
    6, 4, 4, 4, 6, 4, 4, 4,
    4, 4, 4, 4, 4, 4,
]

ROPE_SEGMENTS = 32
ROPE_TURN_MASK = 54
ROPE_TABLE_BYTES = 86

# VIC playfield is 75% of Spectrum width — scale horizontal (rotate) steps.
ROPE_X_SCALE = 0.75


def scale_rotates(rotates: list[int], factor: float = ROPE_X_SCALE) -> list[int]:
    """Scale rotate nybbles so their sum is factor × Spectrum total (integer steps)."""
    target = round(sum(rotates) * factor)
    floats = [r * factor for r in rotates]
    scaled = [int(f) for f in floats]
    diff = target - sum(scaled)
    if diff > 0:
        order = sorted(
            ((floats[i] - int(floats[i]), i) for i in range(len(rotates)) if rotates[i] > 0),
            reverse=True,
        )
        for _, i in order[:diff]:
            scaled[i] += 1
    elif diff < 0:
        order = sorted(
            ((floats[i] - int(floats[i]), i) for i in range(len(rotates)) if scaled[i] > 0),
        )
        for _, i in order[:-diff]:
            scaled[i] = max(0, scaled[i] - 1)
    for i, rot in enumerate(scaled):
        if not 0 <= rot <= 15:
            raise ValueError(f"scaled rotate out of range at {i}: {rot}")
    return scaled


def pack_table() -> bytes:
    if len(ROPE_ROTATE) != ROPE_TABLE_BYTES or len(ROPE_YOFF) != ROPE_TABLE_BYTES:
        raise ValueError("rotate/yoff tables must be 86 bytes each")
    rotates = scale_rotates(ROPE_ROTATE)
    out = bytearray()
    for rot, yoff in zip(rotates, ROPE_YOFF):
        if not 0 <= rot <= 15 or not 0 <= yoff <= 15:
            raise ValueError(f"nybble out of range: rot={rot} yoff={yoff}")
        out.append((rot << 4) | yoff)
    return bytes(out)


def validate_sliding_window(table: bytes) -> None:
    """Every frame F in 0..54 must have valid table[F..F+31] lookups."""
    errors: list[str] = []
    for f in range(ROPE_TURN_MASK + 1):
        for s in range(ROPE_SEGMENTS):
            idx = (f & 0x7F) + s
            if idx >= len(table):
                errors.append(f"F={f} S={s}: index {idx} out of range")
    if errors:
        raise ValueError("sliding window validation failed:\n" + "\n".join(errors))


def emit_asm(table: bytes, path: Path) -> None:
    lines = [
        "; Rope animation table — 86 bytes, auto-generated by tools/rope_table.py",
        "; high nybble = rotate count, low nybble = y row step",
        f"ROPE_TABLE_BYTES = {ROPE_TABLE_BYTES}",
        "",
        "rope_table",
    ]
    for i in range(0, len(table), 8):
        chunk = table[i : i + 8]
        hexes = ", ".join(f"${b:02x}" for b in chunk)
        lines.append(f"    !byte {hexes}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    table = pack_table()
    validate_sliding_window(table)
    root = Path(__file__).resolve().parent.parent
    emit_asm(table, root / "rope_table.asm")
    (root / "tools" / "rope_table.bin").write_bytes(table)
    rot_sum = sum(scale_rotates(ROPE_ROTATE))
    spec_sum = sum(ROPE_ROTATE)
    print(f"rope_table.asm + rope_table.bin ({len(table)} bytes)")
    print(f"rotate sum {rot_sum} ({100 * rot_sum / spec_sum:.0f}% of Spectrum {spec_sum})")
    print("sliding window OK for F=0..54, S=0..31")
    return 0


if __name__ == "__main__":
    sys.exit(main())
