; JSW-Tape canonical tile UDG pool — generated by mkcatalogue.py
; Loader copies 8 B from udg_pool_* + index*8 into character RAM.

udg_pool_counts
; floor wall nasty ramp belt pickup — slots used (not padded)
    !byte 18, 18, 12, 8, 8, 24

udg_pool_floor = udg_canonical_pool + 0
udg_pool_wall = udg_canonical_pool + 144
udg_pool_nasty = udg_canonical_pool + 288
udg_pool_ramp = udg_canonical_pool + 384
udg_pool_belt = udg_canonical_pool + 448
udg_pool_pickup = udg_canonical_pool + 512

udg_canonical_pool
; 704 bytes (88 slots x 8 B)
    !byte $ff, $bf, $f6, $9b, $6d, $d2, $69, $00, $ff, $ff, $5a, $99, $bd, $5a, $3c, $5a
    !byte $ff, $a5, $52, $24, $42, $22, $40, $04, $ce, $ff, $00, $e7, $00, $7f, $00, $fb
    !byte $ff, $ff, $bf, $fb, $ff, $ef, $ff, $fe, $ff, $44, $44, $ff, $11, $11, $ff, $00
    !byte $fe, $55, $2a, $aa, $55, $aa, $aa, $ff, $ff, $ff, $00, $00, $00, $00, $00, $00
    !byte $ff, $5d, $ff, $ff, $ff, $b9, $ff, $6c, $a0, $40, $80, $00, $00, $00, $00, $00
    !byte $5f, $eb, $7d, $af, $f5, $be, $d7, $fa, $80, $40, $20, $50, $48, $54, $52, $55
    !byte $01, $1e, $06, $7a, $1a, $e8, $68, $a0, $b6, $b6, $b6, $b6, $b6, $b6, $b6, $b6
    !byte $80, $c0, $e0, $d0, $58, $9c, $de, $cd, $ad, $52, $29, $00, $01, $02, $00, $00
    !byte $aa, $55, $aa, $ff, $ff, $55, $aa, $55, $b5, $aa, $55, $4a, $25, $42, $01, $02
    !byte $e0, $55, $ff, $aa, $07, $aa, $ff, $55, $69, $90, $90, $69, $96, $69, $69, $96
    !byte $b5, $d6, $da, $b6, $6d, $5b, $da, $6b, $cc, $ee, $bb, $33, $cc, $ee, $bb, $33
    !byte $11, $ee, $93, $6d, $ee, $36, $dd, $63, $15, $f1, $8f, $a8, $8a, $f8, $1f, $15
    !byte $bb, $bb, $44, $bb, $bb, $bb, $44, $bb, $0e, $c6, $95, $b0, $36, $86, $c0, $ed
    !byte $bd, $5a, $a5, $db, $db, $a5, $5a, $bd, $44, $aa, $11, $44, $11, $aa, $44, $11
    !byte $ff, $d5, $ab, $ff, $ff, $5d, $ba, $ff, $07, $ff, $fc, $38, $18, $10, $20, $00
    !byte $d8, $09, $ff, $23, $2e, $fb, $88, $7f, $09, $12, $0a, $1f, $e4, $08, $08, $08
    !byte $ff, $60, $0e, $f0, $03, $3c, $c7, $38, $bb, $ff, $6d, $db, $7f, $d7, $7d, $af
    !byte $22, $77, $22, $88, $22, $77, $22, $88, $40, $ea, $ff, $ae, $04, $ae, $ff, $ea
    !byte $24, $12, $44, $aa, $55, $aa, $5b, $ff, $bd, $7e, $18, $7e, $a5, $81, $c3, $bd
    !byte $00, $00, $00, $00, $7c, $fe, $7f, $3e, $30, $60, $c0, $80, $00, $00, $00, $00
    !byte $bf, $7d, $ad, $ff, $ff, $ff, $ff, $ff, $01, $81, $06, $58, $20, $40, $88, $82
    !byte $ff, $3f, $03, $1f, $7f, $1f, $03, $3f, $04, $04, $04, $88, $50, $20, $10, $08
    !byte $81, $7e, $5a, $66, $66, $5a, $7e, $81, $88, $a9, $a9, $bb, $bf, $bf, $bf, $5e
    !byte $7e, $bf, $bf, $6e, $2c, $2c, $ad, $ff, $51, $55, $54, $55, $15, $55, $45, $55
    !byte $03, $00, $0c, $00, $30, $00, $c0, $00, $80, $40, $20, $10, $08, $04, $02, $01
    !byte $40, $90, $24, $48, $12, $24, $09, $02, $40, $00, $10, $00, $04, $00, $01, $00
    !byte $03, $03, $0f, $0f, $3f, $3f, $ff, $ff, $80, $c0, $a0, $f0, $f8, $5c, $ba, $55
    !byte $07, $02, $3c, $08, $70, $20, $c0, $80, $80, $40, $e0, $30, $a8, $d4, $22, $89
    !byte $5a, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $55, $55, $55, $55, $51, $5f, $40, $aa
    !byte $e0, $aa, $38, $01, $83, $c7, $7c, $10, $f0, $aa, $3c, $aa, $55, $aa, $55, $aa
    !byte $aa, $55, $aa, $55, $aa, $55, $aa, $55, $f6, $ff, $e7, $00, $00, $00, $00, $00
    !byte $cc, $00, $cc, $ff, $00, $ff, $55, $ff, $33, $40, $33, $00, $1e, $55, $aa, $44
    !byte $1f, $04, $0a, $77, $87, $b1, $aa, $0a, $18, $24, $a4, $ca, $95, $0a, $15, $0a
    !byte $f0, $f0, $78, $b8, $4c, $32, $0d, $03, $00, $19, $f9, $1f, $00, $19, $ff, $1f
    !byte $01, $02, $05, $0a, $54, $28, $30, $48, $ce, $f1, $b9, $d5, $ef, $d7, $bb, $ff
    !byte $70, $8c, $72, $fa, $ef, $ad, $25, $21, $05, $38, $45, $82, $82, $82, $44, $38
    !byte $bf, $bf, $bb, $b1, $bb, $bb, $bf, $bf, $00, $00, $00, $0a, $0d, $3c, $f2, $c0
    !byte $20, $40, $a0, $18, $16, $09, $08, $04, $ff, $49, $49, $49, $49, $49, $49, $ff
    !byte $02, $14, $2e, $55, $2a, $45, $2a, $14, $40, $a0, $f0, $f8, $fc, $7a, $25, $02
    !byte $30, $3c, $4f, $43, $82, $86, $e4, $fc, $40, $a0, $5c, $22, $21, $22, $14, $08
    !byte $04, $05, $0b, $0b, $17, $37, $6f, $ef, $70, $20, $20, $50, $50, $88, $88, $88
    !byte $1e, $2d, $37, $7b, $6d, $5e, $b8, $c0, $18, $18, $f8, $3c, $7e, $60, $60, $7e
    !byte $ac, $ae, $01, $ad, $ad, $02, $ac, $58, $81, $42, $24, $18, $3c, $18, $3c, $c3
    !byte $74, $38, $66, $bf, $bf, $9d, $42, $3c, $00, $00, $18, $14, $1a, $35, $6b, $d0
